// 자동 생성 파일 — 원본: 대수_유형분류.hwpx, 미적분1_유형분류.hwpx, 확률과통계_유형분류.hwpx
// 수정 시 원본 HWP 문서를 먼저 고치고 다시 생성할 것.
//
// 구조: 과목 > l1(대단원) > l2(중단원) > l3(소단원) > 세부유형
// - groupId(소단원) 단위로 1차 분류하고, 그 안에서 세부유형을 2차 분류한다 (FR-401).
// - label: 화면 표시용. $...$ 구간은 KaTeX로 렌더링한다.
// - plain: 검색·AI 프롬프트 투입용(수식을 텍스트로 치환).
// - hwp:   원본 한글 수식 스크립트 보존.

import type { SubjectSlug } from './subjects';

export interface UnitGroup {
  id: string; subject: SubjectSlug; l1: string; l2: string; l3: string; count: number;
}
export interface UnitType {
  id: string; groupId: string; subject: SubjectSlug; label: string; plain: string; hwp: string;
}

export const UNIT_GROUPS: UnitGroup[] = [
  { id: 'ALG-01', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수와 로그', l3: '거듭제곱과 거듭제곱근', count: 4 },
  { id: 'ALG-02', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수와 로그', l3: '지수의 확장과 지수법칙', count: 11 },
  { id: 'ALG-03', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수와 로그', l3: '로그의 뜻과 성질', count: 14 },
  { id: 'ALG-04', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수와 로그', l3: '상용로그', count: 10 },
  { id: 'ALG-05', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수함수와 로그함수', l3: '지수함수의 뜻과 그래프', count: 12 },
  { id: 'ALG-06', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수함수와 로그함수', l3: '로그함수의 뜻과 그래프', count: 14 },
  { id: 'ALG-07', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수함수와 로그함수', l3: '지수함수의 활용', count: 12 },
  { id: 'ALG-08', subject: 'algebra', l1: '지수함수와 로그함수', l2: '지수함수와 로그함수', l3: '로그함수의 활용', count: 14 },
  { id: 'ALG-09', subject: 'algebra', l1: '삼각함수', l2: '삼각함수', l3: '일반각과 호도법', count: 8 },
  { id: 'ALG-10', subject: 'algebra', l1: '삼각함수', l2: '삼각함수', l3: '삼각함수', count: 9 },
  { id: 'ALG-11', subject: 'algebra', l1: '삼각함수', l2: '삼각함수', l3: '삼각함수의 그래프', count: 24 },
  { id: 'ALG-12', subject: 'algebra', l1: '삼각함수', l2: '사인법칙과 코사인법칙', l3: '사인법칙과 코사인법칙', count: 17 },
  { id: 'ALG-13', subject: 'algebra', l1: '수열', l2: '등차수열과 등비수열', l3: '수열의 뜻', count: 1 },
  { id: 'ALG-14', subject: 'algebra', l1: '수열', l2: '등차수열과 등비수열', l3: '등차수열', count: 13 },
  { id: 'ALG-15', subject: 'algebra', l1: '수열', l2: '등차수열과 등비수열', l3: '등비수열', count: 14 },
  { id: 'ALG-16', subject: 'algebra', l1: '수열', l2: '수열의 합', l3: '합의 기호 ∑', count: 5 },
  { id: 'ALG-17', subject: 'algebra', l1: '수열', l2: '수열의 합', l3: '여러 가지 수열의 합', count: 12 },
  { id: 'ALG-18', subject: 'algebra', l1: '수열', l2: '수학적 귀납법', l3: '수열의 귀납적 정의', count: 9 },
  { id: 'ALG-19', subject: 'algebra', l1: '수열', l2: '수학적 귀납법', l3: '수학적 귀납법', count: 4 },
  { id: 'CAL-01', subject: 'calculus1', l1: '함수의 극한과 연속', l2: '함수의 극한', l3: '함수의 극한', count: 8 },
  { id: 'CAL-02', subject: 'calculus1', l1: '함수의 극한과 연속', l2: '함수의 극한', l3: '함수의 극한값의 계산', count: 11 },
  { id: 'CAL-03', subject: 'calculus1', l1: '함수의 극한과 연속', l2: '함수의 연속', l3: '함수의 연속', count: 5 },
  { id: 'CAL-04', subject: 'calculus1', l1: '함수의 극한과 연속', l2: '함수의 연속', l3: '연속함수의 성질', count: 15 },
  { id: 'CAL-05', subject: 'calculus1', l1: '미분', l2: '미분계수와 도함수', l3: '미분계수', count: 13 },
  { id: 'CAL-06', subject: 'calculus1', l1: '미분', l2: '미분계수와 도함수', l3: '도함수', count: 16 },
  { id: 'CAL-07', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '접선의 방정식', count: 18 },
  { id: 'CAL-08', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '평균값 정리', count: 5 },
  { id: 'CAL-09', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '함수의 증가·감소, 극대·극소', count: 10 },
  { id: 'CAL-10', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '함수의 그래프', count: 15 },
  { id: 'CAL-11', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '방정식과 부등식에서의 활용', count: 14 },
  { id: 'CAL-12', subject: 'calculus1', l1: '미분', l2: '도함수의 활용', l3: '속도와 가속도', count: 11 },
  { id: 'CAL-13', subject: 'calculus1', l1: '적분', l2: '부정적분과 정적분', l3: '부정적분', count: 21 },
  { id: 'CAL-14', subject: 'calculus1', l1: '적분', l2: '부정적분과 정적분', l3: '정적분', count: 23 },
  { id: 'CAL-15', subject: 'calculus1', l1: '적분', l2: '정적분의 활용', l3: '넓이', count: 13 },
  { id: 'CAL-16', subject: 'calculus1', l1: '적분', l2: '정적분의 활용', l3: '속도와 거리', count: 4 },
  { id: 'STA-01', subject: 'statistics', l1: '경우의 수', l2: '순열과 조합', l3: '여러 가지 순열', count: 8 },
  { id: 'STA-02', subject: 'statistics', l1: '경우의 수', l2: '순열과 조합', l3: '중복조합', count: 6 },
  { id: 'STA-03', subject: 'statistics', l1: '경우의 수', l2: '이항정리', l3: '이항정리', count: 9 },
  { id: 'STA-04', subject: 'statistics', l1: '확률', l2: '확률의 뜻과 활용', l3: '확률의 뜻', count: 10 },
  { id: 'STA-05', subject: 'statistics', l1: '확률', l2: '확률의 뜻과 활용', l3: '확률의 덧셈정리', count: 5 },
  { id: 'STA-06', subject: 'statistics', l1: '확률', l2: '조건부 확률', l3: '조건부확률', count: 6 },
  { id: 'STA-07', subject: 'statistics', l1: '확률', l2: '조건부 확률', l3: '사건의 독립과 종속', count: 6 },
  { id: 'STA-08', subject: 'statistics', l1: '통계', l2: '확률분포', l3: '확률변수와 확률분포', count: 9 },
  { id: 'STA-09', subject: 'statistics', l1: '통계', l2: '확률분포', l3: '이산확률변수의 기댓값과 표준편차', count: 5 },
  { id: 'STA-10', subject: 'statistics', l1: '통계', l2: '확률분포', l3: '이항분포', count: 6 },
  { id: 'STA-11', subject: 'statistics', l1: '통계', l2: '확률분포', l3: '정규분포', count: 15 },
  { id: 'STA-12', subject: 'statistics', l1: '통계', l2: '통계적 추정', l3: '모집단과 표본', count: 1 },
  { id: 'STA-13', subject: 'statistics', l1: '통계', l2: '통계적 추정', l3: '모평균의 추정', count: 15 },
  { id: 'STA-14', subject: 'statistics', l1: '통계', l2: '통계적 추정', l3: '모비율의 추정', count: 5 },
];

export const UNIT_TYPES: UnitType[] = [
  { id: 'ALG-01-01', groupId: 'ALG-01', subject: 'algebra', label: '거듭제곱근', plain: '거듭제곱근', hwp: '거듭제곱근' },
  { id: 'ALG-01-02', groupId: 'ALG-01', subject: 'algebra', label: '거듭제곱근의 계산', plain: '거듭제곱근의 계산', hwp: '거듭제곱근의 계산' },
  { id: 'ALG-01-03', groupId: 'ALG-01', subject: 'algebra', label: '문자를 포함한 거듭제곱근의 계산', plain: '문자를 포함한 거듭제곱근의 계산', hwp: '문자를 포함한 거듭제곱근의 계산' },
  { id: 'ALG-01-04', groupId: 'ALG-01', subject: 'algebra', label: '거듭제곱근의 대소 비교', plain: '거듭제곱근의 대소 비교', hwp: '거듭제곱근의 대소 비교' },
  { id: 'ALG-02-01', groupId: 'ALG-02', subject: 'algebra', label: '지수가 정수인 식의 계산', plain: '지수가 정수인 식의 계산', hwp: '지수가 정수인 식의 계산' },
  { id: 'ALG-02-02', groupId: 'ALG-02', subject: 'algebra', label: '지수가 실수인 식의 계산', plain: '지수가 실수인 식의 계산', hwp: '지수가 실수인 식의 계산' },
  { id: 'ALG-02-03', groupId: 'ALG-02', subject: 'algebra', label: '거듭제곱근을 지수로 나타내기', plain: '거듭제곱근을 지수로 나타내기', hwp: '거듭제곱근을 지수로 나타내기' },
  { id: 'ALG-02-04', groupId: 'ALG-02', subject: 'algebra', label: '거듭제곱을 주어진 문자로 나타내기', plain: '거듭제곱을 주어진 문자로 나타내기', hwp: '거듭제곱을 주어진 문자로 나타내기' },
  { id: 'ALG-02-05', groupId: 'ALG-02', subject: 'algebra', label: '$a^r$이 자연수가 될 조건', plain: 'a^r이 자연수가 될 조건', hwp: '$a^r`$이 자연수가 될 조건' },
  { id: 'ALG-02-06', groupId: 'ALG-02', subject: 'algebra', label: '지수법칙과 곱셈 공식', plain: '지수법칙과 곱셈 공식', hwp: '지수법칙과 곱셈 공식' },
  { id: 'ALG-02-07', groupId: 'ALG-02', subject: 'algebra', label: '$a^x+a^{-x}$꼴의 식의 값 구하기', plain: 'a^x+a^{-x}꼴의 식의 값 구하기', hwp: '$a^x + a^-x `$꼴의 식의 값 구하기' },
  { id: 'ALG-02-08', groupId: 'ALG-02', subject: 'algebra', label: '$\\frac{a^x-a^{-x}}{a^x+a^{-x}}$꼴의 식의 값 구하기', plain: '\\frac{a^x-a^{-x}}{a^x+a^{-x}}꼴의 식의 값 구하기', hwp: '${a^x - a^-x} over{a^x +a^-x}  `$꼴의 식의 값 구하기' },
  { id: 'ALG-02-09', groupId: 'ALG-02', subject: 'algebra', label: '$a^x=k$가 주어질 때 식의 값 구하기', plain: 'a^x=k가 주어질 때 식의 값 구하기', hwp: '$a^x =k`$가 주어질 때 식의 값 구하기' },
  { id: 'ALG-02-10', groupId: 'ALG-02', subject: 'algebra', label: '$a^x = b^y$가 주어질 때 식의 값 구하기', plain: 'a^x = b^y가 주어질 때 식의 값 구하기', hwp: '$a^x = b^y`$가 주어질 때 식의 값 구하기' },
  { id: 'ALG-02-11', groupId: 'ALG-02', subject: 'algebra', label: '지수의 실생활에의 활용', plain: '지수의 실생활에의 활용', hwp: '지수의 실생활에의 활용' },
  { id: 'ALG-03-01', groupId: 'ALG-03', subject: 'algebra', label: '로그의 정의', plain: '로그의 정의', hwp: '로그의 정의' },
  { id: 'ALG-03-02', groupId: 'ALG-03', subject: 'algebra', label: '로그의 밑과 진수의 조건', plain: '로그의 밑과 진수의 조건', hwp: '로그의 밑과 진수의 조건' },
  { id: 'ALG-03-03', groupId: 'ALG-03', subject: 'algebra', label: '로그의 성질', plain: '로그의 성질', hwp: '로그의 성질' },
  { id: 'ALG-03-04', groupId: 'ALG-03', subject: 'algebra', label: '로그의 밑의 변환', plain: '로그의 밑의 변환', hwp: '로그의 밑의 변환' },
  { id: 'ALG-03-05', groupId: 'ALG-03', subject: 'algebra', label: '로그의 여러 가지 성질', plain: '로그의 여러 가지 성질', hwp: '로그의 여러 가지 성질' },
  { id: 'ALG-03-06', groupId: 'ALG-03', subject: 'algebra', label: '로그에 대한 증명', plain: '로그에 대한 증명', hwp: '로그에 대한 증명' },
  { id: 'ALG-03-07', groupId: 'ALG-03', subject: 'algebra', label: '로그의 성질의 활용(1) $\\log_a b = c$가 주어진 경우', plain: '로그의 성질의 활용(1) log_a b = c가 주어진 경우', hwp: '로그의 성질의 활용(1) $log_a b = c$가 주어진 경우' },
  { id: 'ALG-03-08', groupId: 'ALG-03', subject: 'algebra', label: '로그의 성질의 활용(2) $a^x = b$가 주어진 경우', plain: '로그의 성질의 활용(2) a^x = b가 주어진 경우', hwp: '로그의 성질의 활용(2) $a^x = b`$가 주어진 경우' },
  { id: 'ALG-03-09', groupId: 'ALG-03', subject: 'algebra', label: '식의 값 구하기', plain: '식의 값 구하기', hwp: '식의 값 구하기' },
  { id: 'ALG-03-10', groupId: 'ALG-03', subject: 'algebra', label: '로그와 이차방정식', plain: '로그와 이차방정식', hwp: '로그와 이차방정식' },
  { id: 'ALG-03-11', groupId: 'ALG-03', subject: 'algebra', label: '로그의 대소 관계', plain: '로그의 대소 관계', hwp: '로그의 대소 관계' },
  { id: 'ALG-03-12', groupId: 'ALG-03', subject: 'algebra', label: '로그의 정수 부분과 소수 부분', plain: '로그의 정수 부분과 소수 부분', hwp: '로그의 정수 부분과 소수 부분' },
  { id: 'ALG-03-13', groupId: 'ALG-03', subject: 'algebra', label: '로그의 값이 자연수가 되도록 하는 조건(1)', plain: '로그의 값이 자연수가 되도록 하는 조건(1)', hwp: '로그의 값이 자연수가 되도록 하는 조건(1)' },
  { id: 'ALG-03-14', groupId: 'ALG-03', subject: 'algebra', label: '로그의 성질의 활용(3) 실생활', plain: '로그의 성질의 활용(3) 실생활', hwp: '로그의 성질의 활용(3) 실생활' },
  { id: 'ALG-04-01', groupId: 'ALG-04', subject: 'algebra', label: '상용로그', plain: '상용로그', hwp: '상용로그' },
  { id: 'ALG-04-02', groupId: 'ALG-04', subject: 'algebra', label: '상용로그의 값', plain: '상용로그의 값', hwp: '상용로그의 값' },
  { id: 'ALG-04-03', groupId: 'ALG-04', subject: 'algebra', label: '가우스가 포함된 로그의 값', plain: '가우스가 포함된 로그의 값', hwp: '가우스가 포함된 로그의 값' },
  { id: 'ALG-04-04', groupId: 'ALG-04', subject: 'algebra', label: '상용로그의 정수 부분과 소수 부분', plain: '상용로그의 정수 부분과 소수 부분', hwp: '상용로그의 정수 부분과 소수 부분' },
  { id: 'ALG-04-05', groupId: 'ALG-04', subject: 'algebra', label: '자리 수 구하기', plain: '자리 수 구하기', hwp: '자리 수 구하기' },
  { id: 'ALG-04-06', groupId: 'ALG-04', subject: 'algebra', label: '최고 자리의 숫자 구하기', plain: '최고 자리의 숫자 구하기', hwp: '최고 자리의 숫자 구하기' },
  { id: 'ALG-04-07', groupId: 'ALG-04', subject: 'algebra', label: '상용로그의 소수 부분의 활용', plain: '상용로그의 소수 부분의 활용', hwp: '상용로그의 소수 부분의 활용' },
  { id: 'ALG-04-08', groupId: 'ALG-04', subject: 'algebra', label: '로그의 값이 자연수가 되도록 하는 조건(2)', plain: '로그의 값이 자연수가 되도록 하는 조건(2)', hwp: '로그의 값이 자연수가 되도록 하는 조건(2)' },
  { id: 'ALG-04-09', groupId: 'ALG-04', subject: 'algebra', label: '상용로그의 실생활에의 활용(1) 관계식이 주어진 경우', plain: '상용로그의 실생활에의 활용(1) 관계식이 주어진 경우', hwp: '상용로그의 실생활에의 활용(1) 관계식이 주어진 경우' },
  { id: 'ALG-04-10', groupId: 'ALG-04', subject: 'algebra', label: '상용로그의 실생활에의 활용(2) 일정하게 증가하거나 감소하는 경우', plain: '상용로그의 실생활에의 활용(2) 일정하게 증가하거나 감소하는 경우', hwp: '상용로그의 실생활에의 활용(2) 일정하게 증가하거나 감소하는 경우' },
  { id: 'ALG-05-01', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 뜻', plain: '지수함수의 뜻', hwp: '지수함수의 뜻' },
  { id: 'ALG-05-02', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 함숫값', plain: '지수함수의 함숫값', hwp: '지수함수의 함숫값' },
  { id: 'ALG-05-03', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 성질', plain: '지수함수의 성질', hwp: '지수함수의 성질' },
  { id: 'ALG-05-04', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 그래프', plain: '지수함수의 그래프', hwp: '지수함수의 그래프' },
  { id: 'ALG-05-05', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 그래프의 평행이동과 대칭이동', plain: '지수함수의 그래프의 평행이동과 대칭이동', hwp: '지수함수의 그래프의 평행이동과 대칭이동' },
  { id: 'ALG-05-06', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 그래프 위의 점', plain: '지수함수의 그래프 위의 점', hwp: '지수함수의 그래프 위의 점' },
  { id: 'ALG-05-07', groupId: 'ALG-05', subject: 'algebra', label: '지수함수를 이용한 수의 대소 비교', plain: '지수함수를 이용한 수의 대소 비교', hwp: '지수함수를 이용한 수의 대소 비교' },
  { id: 'ALG-05-08', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 최대·최소(1) $y=a^{px+q}+r$꼴', plain: '지수함수의 최대·최소(1) y=a^{px+q}+r꼴', hwp: '지수함수의 최대·최소(1) $y=a^{px+q} +r`$꼴' },
  { id: 'ALG-05-09', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 최대·최소(2) $y=a^{px^2+qx+r}$꼴', plain: '지수함수의 최대·최소(2) y=a^{px^2+qx+r}꼴', hwp: '지수함수의 최대·최소(2) $y=a^{px^2 +qx +r}`$꼴' },
  { id: 'ALG-05-10', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 최대·최소(3) $a^x$꼴이 반복되는 경우', plain: '지수함수의 최대·최소(3) a^x꼴이 반복되는 경우', hwp: '지수함수의 최대·최소(3) $a^x`$꼴이 반복되는 경우' },
  { id: 'ALG-05-11', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 최대·최소(4) 산술평균과 기하평균을 이용', plain: '지수함수의 최대·최소(4) 산술평균과 기하평균을 이용', hwp: '지수함수의 최대·최소(4) 산술평균과 기하평균을 이용' },
  { id: 'ALG-05-12', groupId: 'ALG-05', subject: 'algebra', label: '지수함수의 최대·최소(5) 그 외', plain: '지수함수의 최대·최소(5) 그 외', hwp: '지수함수의 최대·최소(5) 그 외' },
  { id: 'ALG-06-01', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 뜻', plain: '로그함수의 뜻', hwp: '로그함수의 뜻' },
  { id: 'ALG-06-02', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 함숫값', plain: '로그함수의 함숫값', hwp: '로그함수의 함숫값' },
  { id: 'ALG-06-03', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 성질', plain: '로그함수의 성질', hwp: '로그함수의 성질' },
  { id: 'ALG-06-04', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 그래프', plain: '로그함수의 그래프', hwp: '로그함수의 그래프' },
  { id: 'ALG-06-05', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 그래프의 평행이동과 대칭이동', plain: '로그함수의 그래프의 평행이동과 대칭이동', hwp: '로그함수의 그래프의 평행이동과 대칭이동' },
  { id: 'ALG-06-06', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 그래프 위의 점', plain: '로그함수의 그래프 위의 점', hwp: '로그함수의 그래프 위의 점' },
  { id: 'ALG-06-07', groupId: 'ALG-06', subject: 'algebra', label: '로그함수를 이용한 수의 대소 비교', plain: '로그함수를 이용한 수의 대소 비교', hwp: '로그함수를 이용한 수의 대소 비교' },
  { id: 'ALG-06-08', groupId: 'ALG-06', subject: 'algebra', label: '지수함수와 로그함수의 역함수', plain: '지수함수와 로그함수의 역함수', hwp: '지수함수와 로그함수의 역함수' },
  { id: 'ALG-06-09', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(1) $y=\\log_a\\left(px+q\\right)+r$꼴', plain: '로그함수의 최대·최소(1) y=\\log_a\\left(px+q\\right)+r꼴', hwp: '로그함수의 최대·최소(1) $y=log_a{left(px+q right)} +r`$꼴' },
  { id: 'ALG-06-10', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(2) $y=\\log_a\\left(px^2+qx+r\\right)$꼴', plain: '로그함수의 최대·최소(2) y=\\log_a\\left(px^2+qx+r\\right)꼴', hwp: '로그함수의 최대·최소(2) $y=log_a{left(px^2 +qx+ r right)}`$꼴' },
  { id: 'ALG-06-11', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(3) $\\log_a x$꼴이 반복되는 경우', plain: '로그함수의 최대·최소(3) log_a x꼴이 반복되는 경우', hwp: '로그함수의 최대·최소(3) $log_a x`$꼴이 반복되는 경우' },
  { id: 'ALG-06-12', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(4) 지수에 로그가 있는 경우', plain: '로그함수의 최대·최소(4) 지수에 로그가 있는 경우', hwp: '로그함수의 최대·최소(4) 지수에 로그가 있는 경우' },
  { id: 'ALG-06-13', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(5) 산술평균과 기하평균을 이용', plain: '로그함수의 최대·최소(5) 산술평균과 기하평균을 이용', hwp: '로그함수의 최대·최소(5) 산술평균과 기하평균을 이용' },
  { id: 'ALG-06-14', groupId: 'ALG-06', subject: 'algebra', label: '로그함수의 최대·최소(6) 그 외', plain: '로그함수의 최대·최소(6) 그 외', hwp: '로그함수의 최대·최소(6) 그 외' },
  { id: 'ALG-07-01', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식(1) 밑을 같게 할 수 있는 경우', plain: '지수방정식(1) 밑을 같게 할 수 있는 경우', hwp: '지수방정식(1) 밑을 같게 할 수 있는 경우' },
  { id: 'ALG-07-02', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식(2) $a^x$꼴이 반복되는 경우', plain: '지수방정식(2) a^x꼴이 반복되는 경우', hwp: '지수방정식(2) $a^x`$꼴이 반복되는 경우' },
  { id: 'ALG-07-03', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식(3) 밑 또는 지수가 같은 경우', plain: '지수방정식(3) 밑 또는 지수가 같은 경우', hwp: '지수방정식(3) 밑 또는 지수가 같은 경우' },
  { id: 'ALG-07-04', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식(4) 연립방정식', plain: '지수방정식(4) 연립방정식', hwp: '지수방정식(4) 연립방정식' },
  { id: 'ALG-07-05', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식의 활용', plain: '지수방정식의 활용', hwp: '지수방정식의 활용' },
  { id: 'ALG-07-06', groupId: 'ALG-07', subject: 'algebra', label: '지수방정식의 실생활에의 활용', plain: '지수방정식의 실생활에의 활용', hwp: '지수방정식의 실생활에의 활용' },
  { id: 'ALG-07-07', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식(1) 밑을 같게 할 수 있는 경우', plain: '지수부등식(1) 밑을 같게 할 수 있는 경우', hwp: '지수부등식(1) 밑을 같게 할 수 있는 경우' },
  { id: 'ALG-07-08', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식(2) $a^x$꼴이 반복되는 경우', plain: '지수부등식(2) a^x꼴이 반복되는 경우', hwp: '지수부등식(2) $a^x`$꼴이 반복되는 경우' },
  { id: 'ALG-07-09', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식(3) 밑에 미지수가 있는 경우', plain: '지수부등식(3) 밑에 미지수가 있는 경우', hwp: '지수부등식(3) 밑에 미지수가 있는 경우' },
  { id: 'ALG-07-10', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식(4) 연립부등식', plain: '지수부등식(4) 연립부등식', hwp: '지수부등식(4) 연립부등식' },
  { id: 'ALG-07-11', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식이 항상 성립할 조건', plain: '지수부등식이 항상 성립할 조건', hwp: '지수부등식이 항상 성립할 조건' },
  { id: 'ALG-07-12', groupId: 'ALG-07', subject: 'algebra', label: '지수부등식의 실생활에의 활용', plain: '지수부등식의 실생활에의 활용', hwp: '지수부등식의 실생활에의 활용' },
  { id: 'ALG-08-01', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식(1) 밑을 같게 할 수 있는 경우', plain: '로그방정식(1) 밑을 같게 할 수 있는 경우', hwp: '로그방정식(1) 밑을 같게 할 수 있는 경우' },
  { id: 'ALG-08-02', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식(2) $\\log_a x$꼴이 반복되는 경우', plain: '로그방정식(2) log_a x꼴이 반복되는 경우', hwp: '로그방정식(2) $log_a x`$꼴이 반복되는 경우' },
  { id: 'ALG-08-03', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식(3) 지수에 로그가 포함되는 경우', plain: '로그방정식(3) 지수에 로그가 포함되는 경우', hwp: '로그방정식(3) 지수에 로그가 포함되는 경우' },
  { id: 'ALG-08-04', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식(4) 연립방정식', plain: '로그방정식(4) 연립방정식', hwp: '로그방정식(4) 연립방정식' },
  { id: 'ALG-08-05', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식의 활용', plain: '로그방정식의 활용', hwp: '로그방정식의 활용' },
  { id: 'ALG-08-06', groupId: 'ALG-08', subject: 'algebra', label: '로그방정식의 실생활에의 활용', plain: '로그방정식의 실생활에의 활용', hwp: '로그방정식의 실생활에의 활용' },
  { id: 'ALG-08-07', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식(1) 밑을 같게 할 수 있는 경우', plain: '로그부등식(1) 밑을 같게 할 수 있는 경우', hwp: '로그부등식(1) 밑을 같게 할 수 있는 경우' },
  { id: 'ALG-08-08', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식(2) 진수에 로그가 있는 경우', plain: '로그부등식(2) 진수에 로그가 있는 경우', hwp: '로그부등식(2) 진수에 로그가 있는 경우' },
  { id: 'ALG-08-09', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식(3) $\\log_a x$꼴이 반복되는 경우', plain: '로그부등식(3) log_a x꼴이 반복되는 경우', hwp: '로그부등식(3) $log_a x`$꼴이 반복되는 경우' },
  { id: 'ALG-08-10', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식(4) 지수에 로그가 있는 경우', plain: '로그부등식(4) 지수에 로그가 있는 경우', hwp: '로그부등식(4) 지수에 로그가 있는 경우' },
  { id: 'ALG-08-11', groupId: 'ALG-08', subject: 'algebra', label: '지수부등식(5) 연립부등식', plain: '지수부등식(5) 연립부등식', hwp: '지수부등식(5) 연립부등식' },
  { id: 'ALG-08-12', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식이 항상 성립할 조건', plain: '로그부등식이 항상 성립할 조건', hwp: '로그부등식이 항상 성립할 조건' },
  { id: 'ALG-08-13', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식이 의 활용', plain: '로그부등식이 의 활용', hwp: '로그부등식이 의 활용' },
  { id: 'ALG-08-14', groupId: 'ALG-08', subject: 'algebra', label: '로그부등식의 실생활에의 활용', plain: '로그부등식의 실생활에의 활용', hwp: '로그부등식의 실생활에의 활용' },
  { id: 'ALG-09-01', groupId: 'ALG-09', subject: 'algebra', label: '일반각', plain: '일반각', hwp: '일반각' },
  { id: 'ALG-09-02', groupId: 'ALG-09', subject: 'algebra', label: '사분면의 각', plain: '사분면의 각', hwp: '사분면의 각' },
  { id: 'ALG-09-03', groupId: 'ALG-09', subject: 'algebra', label: '육십분법과 호도법', plain: '육십분법과 호도법', hwp: '육십분법과 호도법' },
  { id: 'ALG-09-04', groupId: 'ALG-09', subject: 'algebra', label: '두 동경의 위치 관계(1) 일치 또는 원점에 대하여 대칭', plain: '두 동경의 위치 관계(1) 일치 또는 원점에 대하여 대칭', hwp: '두 동경의 위치 관계(1) 일치 또는 원점에 대하여 대칭' },
  { id: 'ALG-09-05', groupId: 'ALG-09', subject: 'algebra', label: '두 동경의 위치 관계(2) 직선에 대하여 대칭', plain: '두 동경의 위치 관계(2) 직선에 대하여 대칭', hwp: '두 동경의 위치 관계(2) 직선에 대하여 대칭' },
  { id: 'ALG-09-06', groupId: 'ALG-09', subject: 'algebra', label: '부채꼴의 호의 길이와 넓이', plain: '부채꼴의 호의 길이와 넓이', hwp: '부채꼴의 호의 길이와 넓이' },
  { id: 'ALG-09-07', groupId: 'ALG-09', subject: 'algebra', label: '부채꼴의 호의 길이와 넓이의 활용', plain: '부채꼴의 호의 길이와 넓이의 활용', hwp: '부채꼴의 호의 길이와 넓이의 활용' },
  { id: 'ALG-09-08', groupId: 'ALG-09', subject: 'algebra', label: '부채꼴의 둘레의 길이와 넓이의 최대·최소', plain: '부채꼴의 둘레의 길이와 넓이의 최대·최소', hwp: '부채꼴의 둘레의 길이와 넓이의 최대·최소' },
  { id: 'ALG-10-01', groupId: 'ALG-10', subject: 'algebra', label: '삼각비', plain: '삼각비', hwp: '삼각비' },
  { id: 'ALG-10-02', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수의 정의(1)', plain: '삼각함수의 정의(1)', hwp: '삼각함수의 정의(1)' },
  { id: 'ALG-10-03', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수의 정의(2)', plain: '삼각함수의 정의(2)', hwp: '삼각함수의 정의(2)' },
  { id: 'ALG-10-04', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수의 값의 부호', plain: '삼각함수의 값의 부호', hwp: '삼각함수의 값의 부호' },
  { id: 'ALG-10-05', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수 사이의 관계(1) 식 간단히 하기', plain: '삼각함수 사이의 관계(1) 식 간단히 하기', hwp: '삼각함수 사이의 관계(1) 식 간단히 하기' },
  { id: 'ALG-10-06', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수 사이의 관계(2) 식의 값 구하기', plain: '삼각함수 사이의 관계(2) 식의 값 구하기', hwp: '삼각함수 사이의 관계(2) 식의 값 구하기' },
  { id: 'ALG-10-07', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수 사이의 관계(3) $\\sin\\theta\\pm\\cos\\theta$, $\\sin\\theta\\cos\\theta$이용', plain: '삼각함수 사이의 관계(3) sinθ±cosθ, sinθcosθ이용', hwp: '삼각함수 사이의 관계(3) $sintheta+-costheta$, $sin` theta cos theta$이용' },
  { id: 'ALG-10-08', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수 사이의 관계의 활용', plain: '삼각함수 사이의 관계의 활용', hwp: '삼각함수 사이의 관계의 활용' },
  { id: 'ALG-10-09', groupId: 'ALG-10', subject: 'algebra', label: '삼각함수와 이차방정식', plain: '삼각함수와 이차방정식', hwp: '삼각함수와 이차방정식' },
  { id: 'ALG-11-01', groupId: 'ALG-11', subject: 'algebra', label: '주기함수', plain: '주기함수', hwp: '주기함수' },
  { id: 'ALG-11-02', groupId: 'ALG-11', subject: 'algebra', label: '함수 $y=\\sin x$, $y=\\cos x$의 그래프의 성질', plain: '함수 y=sin x, y=cos x의 그래프의 성질', hwp: '함수 $y=sinx$, $y=cosx`$의 그래프의 성질' },
  { id: 'ALG-11-03', groupId: 'ALG-11', subject: 'algebra', label: '함수 $y=\\tan x$의 그래프의 성질', plain: '함수 y=tan x의 그래프의 성질', hwp: '함수 $y=tanx`$의 그래프의 성질' },
  { id: 'ALG-11-04', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 그래프', plain: '삼각함수의 그래프', hwp: '삼각함수의 그래프' },
  { id: 'ALG-11-05', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 값의 대소 비교', plain: '삼각함수의 값의 대소 비교', hwp: '삼각함수의 값의 대소 비교' },
  { id: 'ALG-11-06', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 그래프의 평행이동과 대칭이동', plain: '삼각함수의 그래프의 평행이동과 대칭이동', hwp: '삼각함수의 그래프의 평행이동과 대칭이동' },
  { id: 'ALG-11-07', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 최대·최소와 주기', plain: '삼각함수의 최대·최소와 주기', hwp: '삼각함수의 최대·최소와 주기' },
  { id: 'ALG-11-08', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 미정계수의 결정(1) 조건이 주어진 경우', plain: '삼각함수의 미정계수의 결정(1) 조건이 주어진 경우', hwp: '삼각함수의 미정계수의 결정(1) 조건이 주어진 경우' },
  { id: 'ALG-11-09', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 미정계수의 결정(2) 그래프가 주어진 경우', plain: '삼각함수의 미정계수의 결정(2) 그래프가 주어진 경우', hwp: '삼각함수의 미정계수의 결정(2) 그래프가 주어진 경우' },
  { id: 'ALG-11-10', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 그래프의 대칭성', plain: '삼각함수의 그래프의 대칭성', hwp: '삼각함수의 그래프의 대칭성' },
  { id: 'ALG-11-11', groupId: 'ALG-11', subject: 'algebra', label: '절댓값 기호를 포함한 삼각함수의 그래프', plain: '절댓값 기호를 포함한 삼각함수의 그래프', hwp: '절댓값 기호를 포함한 삼각함수의 그래프' },
  { id: 'ALG-11-12', groupId: 'ALG-11', subject: 'algebra', label: '여러 가지 각의 삼각함수(1) 그 외', plain: '여러 가지 각의 삼각함수(1) 그 외', hwp: '여러 가지 각의 삼각함수(1) 그 외' },
  { id: 'ALG-11-13', groupId: 'ALG-11', subject: 'algebra', label: '여러 가지 각의 삼각함수(2) 일정하게 증가하는 각', plain: '여러 가지 각의 삼각함수(2) 일정하게 증가하는 각', hwp: '여러 가지 각의 삼각함수(2) 일정하게 증가하는 각' },
  { id: 'ALG-11-14', groupId: 'ALG-11', subject: 'algebra', label: '여러 가지 각의 삼각함수(3) 도형에의 활용', plain: '여러 가지 각의 삼각함수(3) 도형에의 활용', hwp: '여러 가지 각의 삼각함수(3) 도형에의 활용' },
  { id: 'ALG-11-15', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수를 포함한 함수의 최대·최소(1) 일차식의 꼴', plain: '삼각함수를 포함한 함수의 최대·최소(1) 일차식의 꼴', hwp: '삼각함수를 포함한 함수의 최대·최소(1) 일차식의 꼴' },
  { id: 'ALG-11-16', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수를 포함한 함수의 최대·최소(2) 분수식의 꼴', plain: '삼각함수를 포함한 함수의 최대·최소(2) 분수식의 꼴', hwp: '삼각함수를 포함한 함수의 최대·최소(2) 분수식의 꼴' },
  { id: 'ALG-11-17', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수를 포함한 함수의 최대·최소(3) 이차식의 꼴', plain: '삼각함수를 포함한 함수의 최대·최소(3) 이차식의 꼴', hwp: '삼각함수를 포함한 함수의 최대·최소(3) 이차식의 꼴' },
  { id: 'ALG-11-18', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 방정식(1) 일차식의 꼴', plain: '삼각함수가 포함된 방정식(1) 일차식의 꼴', hwp: '삼각함수가 포함된 방정식(1) 일차식의 꼴' },
  { id: 'ALG-11-19', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 방정식(2) 이차식의 꼴', plain: '삼각함수가 포함된 방정식(2) 이차식의 꼴', hwp: '삼각함수가 포함된 방정식(2) 이차식의 꼴' },
  { id: 'ALG-11-20', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수의 그래프와 삼각방정식의 실근', plain: '삼각함수의 그래프와 삼각방정식의 실근', hwp: '삼각함수의 그래프와 삼각방정식의 실근' },
  { id: 'ALG-11-21', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 방정식의 근의 조건', plain: '삼각함수가 포함된 방정식의 근의 조건', hwp: '삼각함수가 포함된 방정식의 근의 조건' },
  { id: 'ALG-11-22', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 부등식(1) 일차식의 꼴', plain: '삼각함수가 포함된 부등식(1) 일차식의 꼴', hwp: '삼각함수가 포함된 부등식(1) 일차식의 꼴' },
  { id: 'ALG-11-23', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 부등식(2) 이차식의 꼴', plain: '삼각함수가 포함된 부등식(2) 이차식의 꼴', hwp: '삼각함수가 포함된 부등식(2) 이차식의 꼴' },
  { id: 'ALG-11-24', groupId: 'ALG-11', subject: 'algebra', label: '삼각함수가 포함된 방정식과 부등식의 활용', plain: '삼각함수가 포함된 방정식과 부등식의 활용', hwp: '삼각함수가 포함된 방정식과 부등식의 활용' },
  { id: 'ALG-12-01', groupId: 'ALG-12', subject: 'algebra', label: '사인법칙', plain: '사인법칙', hwp: '사인법칙' },
  { id: 'ALG-12-02', groupId: 'ALG-12', subject: 'algebra', label: '사인법칙과 삼각형의 외접원', plain: '사인법칙과 삼각형의 외접원', hwp: '사인법칙과 삼각형의 외접원' },
  { id: 'ALG-12-03', groupId: 'ALG-12', subject: 'algebra', label: '사인법칙의 변형', plain: '사인법칙의 변형', hwp: '사인법칙의 변형' },
  { id: 'ALG-12-04', groupId: 'ALG-12', subject: 'algebra', label: '삼각형의 모양 결정(1) 사인법칙 이용', plain: '삼각형의 모양 결정(1) 사인법칙 이용', hwp: '삼각형의 모양 결정(1) 사인법칙 이용' },
  { id: 'ALG-12-05', groupId: 'ALG-12', subject: 'algebra', label: '사인법칙의 활용', plain: '사인법칙의 활용', hwp: '사인법칙의 활용' },
  { id: 'ALG-12-06', groupId: 'ALG-12', subject: 'algebra', label: '코사인법칙', plain: '코사인법칙', hwp: '코사인법칙' },
  { id: 'ALG-12-07', groupId: 'ALG-12', subject: 'algebra', label: '코사인법칙의 변형', plain: '코사인법칙의 변형', hwp: '코사인법칙의 변형' },
  { id: 'ALG-12-08', groupId: 'ALG-12', subject: 'algebra', label: '삼각형의 최대각, 최소각', plain: '삼각형의 최대각, 최소각', hwp: '삼각형의 최대각, 최소각' },
  { id: 'ALG-12-09', groupId: 'ALG-12', subject: 'algebra', label: '사인법칙과 코사인법칙', plain: '사인법칙과 코사인법칙', hwp: '사인법칙과 코사인법칙' },
  { id: 'ALG-12-10', groupId: 'ALG-12', subject: 'algebra', label: '삼각형의 모양 결정(2) 코사인법칙 이용', plain: '삼각형의 모양 결정(2) 코사인법칙 이용', hwp: '삼각형의 모양 결정(2) 코사인법칙 이용' },
  { id: 'ALG-12-11', groupId: 'ALG-12', subject: 'algebra', label: '코사인법칙의 활용', plain: '코사인법칙의 활용', hwp: '코사인법칙의 활용' },
  { id: 'ALG-12-12', groupId: 'ALG-12', subject: 'algebra', label: '삼각형의 넓이', plain: '삼각형의 넓이', hwp: '삼각형의 넓이' },
  { id: 'ALG-12-13', groupId: 'ALG-12', subject: 'algebra', label: '외접원의 반지름의 길이와 삼각형의 넓이', plain: '외접원의 반지름의 길이와 삼각형의 넓이', hwp: '외접원의 반지름의 길이와 삼각형의 넓이' },
  { id: 'ALG-12-14', groupId: 'ALG-12', subject: 'algebra', label: '헤론의 공식', plain: '헤론의 공식', hwp: '헤론의 공식' },
  { id: 'ALG-12-15', groupId: 'ALG-12', subject: 'algebra', label: '사각형의 넓이(1) 삼각형 이용', plain: '사각형의 넓이(1) 삼각형 이용', hwp: '사각형의 넓이(1) 삼각형 이용' },
  { id: 'ALG-12-16', groupId: 'ALG-12', subject: 'algebra', label: '평행사변형의 넓이', plain: '평행사변형의 넓이', hwp: '평행사변형의 넓이' },
  { id: 'ALG-12-17', groupId: 'ALG-12', subject: 'algebra', label: '사각형의 넓이(2) 대각선 이용', plain: '사각형의 넓이(2) 대각선 이용', hwp: '사각형의 넓이(2) 대각선 이용' },
  { id: 'ALG-13-01', groupId: 'ALG-13', subject: 'algebra', label: '수열의 일반항', plain: '수열의 일반항', hwp: '수열의 일반항' },
  { id: 'ALG-14-01', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 일반항', plain: '등차수열의 일반항', hwp: '등차수열의 일반항' },
  { id: 'ALG-14-02', groupId: 'ALG-14', subject: 'algebra', label: '항 사이의 관계가 주어진 등차수열', plain: '항 사이의 관계가 주어진 등차수열', hwp: '항 사이의 관계가 주어진 등차수열' },
  { id: 'ALG-14-03', groupId: 'ALG-14', subject: 'algebra', label: '조건을 만족시키는 등차수열의 항 구하기', plain: '조건을 만족시키는 등차수열의 항 구하기', hwp: '조건을 만족시키는 등차수열의 항 구하기' },
  { id: 'ALG-14-04', groupId: 'ALG-14', subject: 'algebra', label: '두 수 사이에 수를 넣어서 만든 등차수열', plain: '두 수 사이에 수를 넣어서 만든 등차수열', hwp: '두 수 사이에 수를 넣어서 만든 등차수열' },
  { id: 'ALG-14-05', groupId: 'ALG-14', subject: 'algebra', label: '등차중항', plain: '등차중항', hwp: '등차중항' },
  { id: 'ALG-14-06', groupId: 'ALG-14', subject: 'algebra', label: '등차수열을 이루는 수', plain: '등차수열을 이루는 수', hwp: '등차수열을 이루는 수' },
  { id: 'ALG-14-07', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합(1) 그 외', plain: '등차수열의 합(1) 그 외', hwp: '등차수열의 합(1) 그 외' },
  { id: 'ALG-14-08', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합', plain: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합', hwp: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합' },
  { id: 'ALG-14-09', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합', plain: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합', hwp: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합' },
  { id: 'ALG-14-10', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합의 활용(1) 등차수열의 합의 최대·최소', plain: '등차수열의 합의 활용(1) 등차수열의 합의 최대·최소', hwp: '등차수열의 합의 활용(1) 등차수열의 합의 최대·최소' },
  { id: 'ALG-14-11', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합의 활용(2) 나머지가 같은 자연수의 합', plain: '등차수열의 합의 활용(2) 나머지가 같은 자연수의 합', hwp: '등차수열의 합의 활용(2) 나머지가 같은 자연수의 합' },
  { id: 'ALG-14-12', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합의 활용(3) 그 외', plain: '등차수열의 합의 활용(3) 그 외', hwp: '등차수열의 합의 활용(3) 그 외' },
  { id: 'ALG-14-13', groupId: 'ALG-14', subject: 'algebra', label: '등차수열의 합과 일반항 사이의 관계', plain: '등차수열의 합과 일반항 사이의 관계', hwp: '등차수열의 합과 일반항 사이의 관계' },
  { id: 'ALG-15-01', groupId: 'ALG-15', subject: 'algebra', label: '등비수열의 일반항', plain: '등비수열의 일반항', hwp: '등비수열의 일반항' },
  { id: 'ALG-15-02', groupId: 'ALG-15', subject: 'algebra', label: '항 사이의 관계가 주어진 등비수열', plain: '항 사이의 관계가 주어진 등비수열', hwp: '항 사이의 관계가 주어진 등비수열' },
  { id: 'ALG-15-03', groupId: 'ALG-15', subject: 'algebra', label: '조건을 만족시키는 등비수열의 항 구하기', plain: '조건을 만족시키는 등비수열의 항 구하기', hwp: '조건을 만족시키는 등비수열의 항 구하기' },
  { id: 'ALG-15-04', groupId: 'ALG-15', subject: 'algebra', label: '두 수 사이에 수를 넣어서 만든 등비수열', plain: '두 수 사이에 수를 넣어서 만든 등비수열', hwp: '두 수 사이에 수를 넣어서 만든 등비수열' },
  { id: 'ALG-15-05', groupId: 'ALG-15', subject: 'algebra', label: '등비중항', plain: '등비중항', hwp: '등비중항' },
  { id: 'ALG-15-06', groupId: 'ALG-15', subject: 'algebra', label: '등비수열을 이루는 수', plain: '등비수열을 이루는 수', hwp: '등비수열을 이루는 수' },
  { id: 'ALG-15-07', groupId: 'ALG-15', subject: 'algebra', label: '등차수열과 등비수열', plain: '등차수열과 등비수열', hwp: '등차수열과 등비수열' },
  { id: 'ALG-15-08', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합(1) 그 외', plain: '등차수열의 합(1) 그 외', hwp: '등차수열의 합(1) 그 외' },
  { id: 'ALG-15-09', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합', plain: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합', hwp: '등차수열의 합(2) 두 수 사이에 수를 넣어서 만든 등차수열의 합' },
  { id: 'ALG-15-10', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합', plain: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합', hwp: '등차수열의 합(3) 부분의 합이 주어진 등차수열의 합' },
  { id: 'ALG-15-11', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합의 활용(1) 그 외', plain: '등차수열의 합의 활용(1) 그 외', hwp: '등차수열의 합의 활용(1) 그 외' },
  { id: 'ALG-15-12', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합의 활용(2) 원리합계', plain: '등차수열의 합의 활용(2) 원리합계', hwp: '등차수열의 합의 활용(2) 원리합계' },
  { id: 'ALG-15-13', groupId: 'ALG-15', subject: 'algebra', label: '등비수열의 합과 일반항 사이의 관계', plain: '등비수열의 합과 일반항 사이의 관계', hwp: '등비수열의 합과 일반항 사이의 관계' },
  { id: 'ALG-15-14', groupId: 'ALG-15', subject: 'algebra', label: '등차수열의 합과 등비수열의 합', plain: '등차수열의 합과 등비수열의 합', hwp: '등차수열의 합과 등비수열의 합' },
  { id: 'ALG-16-01', groupId: 'ALG-16', subject: 'algebra', label: '합의 기호 ∑', plain: '합의 기호 ∑', hwp: '합의 기호 ∑' },
  { id: 'ALG-16-02', groupId: 'ALG-16', subject: 'algebra', label: '특정한 값이 반복되는 수열의 합', plain: '특정한 값이 반복되는 수열의 합', hwp: '특정한 값이 반복되는 수열의 합' },
  { id: 'ALG-16-03', groupId: 'ALG-16', subject: 'algebra', label: '∑의 성질', plain: '∑의 성질', hwp: '∑의 성질' },
  { id: 'ALG-16-04', groupId: 'ALG-16', subject: 'algebra', label: '$\\sum_{k=1}^{n} r^k$의 꼴의 계산', plain: '∑(k=1~n) r^k의 꼴의 계산', hwp: '$sum_k=1^n r^k`$의 꼴의 계산' },
  { id: 'ALG-16-05', groupId: 'ALG-16', subject: 'algebra', label: '∑와 등차수열, 등비수열', plain: '∑와 등차수열, 등비수열', hwp: '∑와 등차수열, 등비수열' },
  { id: 'ALG-17-01', groupId: 'ALG-17', subject: 'algebra', label: '자연수의 거듭제곱의 합', plain: '자연수의 거듭제곱의 합', hwp: '자연수의 거듭제곱의 합' },
  { id: 'ALG-17-02', groupId: 'ALG-17', subject: 'algebra', label: '∑를 여러 개 포함한 식', plain: '∑를 여러 개 포함한 식', hwp: '∑를 여러 개 포함한 식' },
  { id: 'ALG-17-03', groupId: 'ALG-17', subject: 'algebra', label: '∑를 이용한 여러 가지 수열의 합', plain: '∑를 이용한 여러 가지 수열의 합', hwp: '∑를 이용한 여러 가지 수열의 합' },
  { id: 'ALG-17-04', groupId: 'ALG-17', subject: 'algebra', label: '∑로 표현된 수열의 합과 일반항 사이의 관계', plain: '∑로 표현된 수열의 합과 일반항 사이의 관계', hwp: '∑로 표현된 수열의 합과 일반항 사이의 관계' },
  { id: 'ALG-17-05', groupId: 'ALG-17', subject: 'algebra', label: '일반항이 k, n에 대한 식인 수열의 합', plain: '일반항이 k, n에 대한 식인 수열의 합', hwp: '일반항이 k, n에 대한 식인 수열의 합' },
  { id: 'ALG-17-06', groupId: 'ALG-17', subject: 'algebra', label: '분수의 꼴인 수열의 합', plain: '분수의 꼴인 수열의 합', hwp: '분수의 꼴인 수열의 합' },
  { id: 'ALG-17-07', groupId: 'ALG-17', subject: 'algebra', label: '근호가 포함된 수열의 합', plain: '근호가 포함된 수열의 합', hwp: '근호가 포함된 수열의 합' },
  { id: 'ALG-17-08', groupId: 'ALG-17', subject: 'algebra', label: '로그가 포함된 수열의 합', plain: '로그가 포함된 수열의 합', hwp: '로그가 포함된 수열의 합' },
  { id: 'ALG-17-09', groupId: 'ALG-17', subject: 'algebra', label: '가우스가 포함된 수열의 합', plain: '가우스가 포함된 수열의 합', hwp: '가우스가 포함된 수열의 합' },
  { id: 'ALG-17-10', groupId: 'ALG-17', subject: 'algebra', label: '여러 가지 수열의 합의 활용', plain: '여러 가지 수열의 합의 활용', hwp: '여러 가지 수열의 합의 활용' },
  { id: 'ALG-17-11', groupId: 'ALG-17', subject: 'algebra', label: '(등차수열) × (등비수열) 꼴의 수열의 합', plain: '(등차수열) × (등비수열) 꼴의 수열의 합', hwp: '(등차수열) × (등비수열) 꼴의 수열의 합' },
  { id: 'ALG-17-12', groupId: 'ALG-17', subject: 'algebra', label: '수열의 항을 묶어 규칙 찾기', plain: '수열의 항을 묶어 규칙 찾기', hwp: '수열의 항을 묶어 규칙 찾기' },
  { id: 'ALG-18-01', groupId: 'ALG-18', subject: 'algebra', label: '등차수열의 귀납적 정의', plain: '등차수열의 귀납적 정의', hwp: '등차수열의 귀납적 정의' },
  { id: 'ALG-18-02', groupId: 'ALG-18', subject: 'algebra', label: '등비수열의 귀납적 정의', plain: '등비수열의 귀납적 정의', hwp: '등비수열의 귀납적 정의' },
  { id: 'ALG-18-03', groupId: 'ALG-18', subject: 'algebra', label: '$a_{n+1}=a_n+f(n)$꼴로 정의된 수열', plain: 'a_{n+1}=a_n+f(n)꼴로 정의된 수열', hwp: '$a_{n+1} = a_n +f(n)`$꼴로 정의된 수열' },
  { id: 'ALG-18-04', groupId: 'ALG-18', subject: 'algebra', label: '$a_{n+1}=a_n\\cdot f(n)$꼴로 정의된 수열', plain: 'a_{n+1}=a_n\\cdot f(n)꼴로 정의된 수열', hwp: '$a_{n+1} = a_n cdotf(n)`$꼴로 정의된 수열' },
  { id: 'ALG-18-05', groupId: 'ALG-18', subject: 'algebra', label: '귀납적으로 정의된 여러 가지 수열', plain: '귀납적으로 정의된 여러 가지 수열', hwp: '귀납적으로 정의된 여러 가지 수열' },
  { id: 'ALG-18-06', groupId: 'ALG-18', subject: 'algebra', label: '같은 수가 반복되는 수열', plain: '같은 수가 반복되는 수열', hwp: '같은 수가 반복되는 수열' },
  { id: 'ALG-18-07', groupId: 'ALG-18', subject: 'algebra', label: '$a_n$과 $S_n$사이의 관계식이 주어진 수열', plain: 'a_n과 S_n사이의 관계식이 주어진 수열', hwp: '$a_n`$과 $S_n`$사이의 관계식이 주어진 수열' },
  { id: 'ALG-18-08', groupId: 'ALG-18', subject: 'algebra', label: '수열의 귀납적 정의의 도형에의 활용', plain: '수열의 귀납적 정의의 도형에의 활용', hwp: '수열의 귀납적 정의의 도형에의 활용' },
  { id: 'ALG-18-09', groupId: 'ALG-18', subject: 'algebra', label: '수열의 귀납적 정의의 실생활에의 활용', plain: '수열의 귀납적 정의의 실생활에의 활용', hwp: '수열의 귀납적 정의의 실생활에의 활용' },
  { id: 'ALG-19-01', groupId: 'ALG-19', subject: 'algebra', label: '수학적 귀납법', plain: '수학적 귀납법', hwp: '수학적 귀납법' },
  { id: 'ALG-19-02', groupId: 'ALG-19', subject: 'algebra', label: '수학적 귀납법(1) 등식의 증명', plain: '수학적 귀납법(1) 등식의 증명', hwp: '수학적 귀납법(1) 등식의 증명' },
  { id: 'ALG-19-03', groupId: 'ALG-19', subject: 'algebra', label: '수학적 귀납법(2) 배수의 증명', plain: '수학적 귀납법(2) 배수의 증명', hwp: '수학적 귀납법(2) 배수의 증명' },
  { id: 'ALG-19-04', groupId: 'ALG-19', subject: 'algebra', label: '수학적 귀납법(3) 부등식의 증명', plain: '수학적 귀납법(3) 부등식의 증명', hwp: '수학적 귀납법(3) 부등식의 증명' },
  { id: 'CAL-01-01', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 수렴과 발산(1) : $x\\to a$일 때', plain: '함수의 수렴과 발산(1) : x→a일 때', hwp: '함수의 수렴과 발산(1) : $x`->`a`$일 때' },
  { id: 'CAL-01-02', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 수렴과 발산(2) : $x\\to\\infty,\\ x\\to-\\infty$일 때', plain: '함수의 수렴과 발산(2) : x→∞, x→-∞일 때', hwp: '함수의 수렴과 발산(2) : $x`->`inf,~x`->`-inf`$일 때' },
  { id: 'CAL-01-03', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 우극한과 좌극한(1) : 함수가 주어진 경우', plain: '함수의 우극한과 좌극한(1) : 함수가 주어진 경우', hwp: '함수의 우극한과 좌극한(1) : 함수가 주어진 경우' },
  { id: 'CAL-01-04', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 우극한과 좌극한(2) : 그래프가 주어진 경우', plain: '함수의 우극한과 좌극한(2) : 그래프가 주어진 경우', hwp: '함수의 우극한과 좌극한(2) : 그래프가 주어진 경우' },
  { id: 'CAL-01-05', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 우극한과 좌극한(3) : 절댓값 기호를 포함한 경우', plain: '함수의 우극한과 좌극한(3) : 절댓값 기호를 포함한 경우', hwp: '함수의 우극한과 좌극한(3) : 절댓값 기호를 포함한 경우' },
  { id: 'CAL-01-06', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 우극한과 좌극한(4) : 가우스 기호를 포함한 경우', plain: '함수의 우극한과 좌극한(4) : 가우스 기호를 포함한 경우', hwp: '함수의 우극한과 좌극한(4) : 가우스 기호를 포함한 경우' },
  { id: 'CAL-01-07', groupId: 'CAL-01', subject: 'calculus1', label: '함수의 극한값의 존재성과 극한값 구하기', plain: '함수의 극한값의 존재성과 극한값 구하기', hwp: '함수의 극한값의 존재성과 극한값 구하기' },
  { id: 'CAL-01-08', groupId: 'CAL-01', subject: 'calculus1', label: '합성함수의 극한', plain: '합성함수의 극한', hwp: '합성함수의 극한' },
  { id: 'CAL-02-01', groupId: 'CAL-02', subject: 'calculus1', label: '함수의 극한에 대한 성질', plain: '함수의 극한에 대한 성질', hwp: '함수의 극한에 대한 성질' },
  { id: 'CAL-02-02', groupId: 'CAL-02', subject: 'calculus1', label: '함수의 극한에 대한 성질 : 합답형', plain: '함수의 극한에 대한 성질 : 합답형', hwp: '함수의 극한에 대한 성질 : 합답형' },
  { id: 'CAL-02-03', groupId: 'CAL-02', subject: 'calculus1', label: '$\\frac{0}{0}$꼴의 극한(1) : 유리식', plain: '0/0꼴의 극한(1) : 유리식', hwp: '$0/0`$꼴의 극한(1) : 유리식' },
  { id: 'CAL-02-04', groupId: 'CAL-02', subject: 'calculus1', label: '$\\frac{0}{0}$꼴의 극한(2) : 무리식', plain: '0/0꼴의 극한(2) : 무리식', hwp: '$0/0`$꼴의 극한(2) : 무리식' },
  { id: 'CAL-02-05', groupId: 'CAL-02', subject: 'calculus1', label: '$\\frac{\\infty}{\\infty}$꼴의 극한', plain: '∞/∞꼴의 극한', hwp: '$inf/inf`$꼴의 극한' },
  { id: 'CAL-02-06', groupId: 'CAL-02', subject: 'calculus1', label: '$\\infty-\\infty$꼴의 극한', plain: '∞-∞꼴의 극한', hwp: '$inf-inf`$꼴의 극한' },
  { id: 'CAL-02-07', groupId: 'CAL-02', subject: 'calculus1', label: '$\\infty\\times 0$꼴의 극한', plain: '∞×0꼴의 극한', hwp: '$inftimes0`$꼴의 극한' },
  { id: 'CAL-02-08', groupId: 'CAL-02', subject: 'calculus1', label: '미정계수의 결정', plain: '미정계수의 결정', hwp: '미정계수의 결정' },
  { id: 'CAL-02-09', groupId: 'CAL-02', subject: 'calculus1', label: '다항함수의 결정', plain: '다항함수의 결정', hwp: '다항함수의 결정' },
  { id: 'CAL-02-10', groupId: 'CAL-02', subject: 'calculus1', label: '함수의 극한의 대소관계', plain: '함수의 극한의 대소관계', hwp: '함수의 극한의 대소관계' },
  { id: 'CAL-02-11', groupId: 'CAL-02', subject: 'calculus1', label: '함수의 극한의 활용', plain: '함수의 극한의 활용', hwp: '함수의 극한의 활용' },
  { id: 'CAL-03-01', groupId: 'CAL-03', subject: 'calculus1', label: '구간의 의미와 표현', plain: '구간의 의미와 표현', hwp: '구간의 의미와 표현' },
  { id: 'CAL-03-02', groupId: 'CAL-03', subject: 'calculus1', label: '함수의 연속과 불연속(1) : 전체 구간에서 함수가 주어진 경우', plain: '함수의 연속과 불연속(1) : 전체 구간에서 함수가 주어진 경우', hwp: '함수의 연속과 불연속(1) : 전체 구간에서 함수가 주어진 경우' },
  { id: 'CAL-03-03', groupId: 'CAL-03', subject: 'calculus1', label: '함수의 연속과 불연속(2) : 함수가 구간별로 주어진 경우', plain: '함수의 연속과 불연속(2) : 함수가 구간별로 주어진 경우', hwp: '함수의 연속과 불연속(2) : 함수가 구간별로 주어진 경우' },
  { id: 'CAL-03-04', groupId: 'CAL-03', subject: 'calculus1', label: '함수가 연속일 조건(1) : 구간별로 주어진 함수가 연속일 조건', plain: '함수가 연속일 조건(1) : 구간별로 주어진 함수가 연속일 조건', hwp: '함수가 연속일 조건(1) : 구간별로 주어진 함수가 연속일 조건' },
  { id: 'CAL-03-05', groupId: 'CAL-03', subject: 'calculus1', label: '함수가 불연속일 조건(1) : 구간별로 주어진 함수가 불연속일 조건', plain: '함수가 불연속일 조건(1) : 구간별로 주어진 함수가 불연속일 조건', hwp: '함수가 불연속일 조건(1) : 구간별로 주어진 함수가 불연속일 조건' },
  { id: 'CAL-04-01', groupId: 'CAL-04', subject: 'calculus1', label: '연속함수의 성질', plain: '연속함수의 성질', hwp: '연속함수의 성질' },
  { id: 'CAL-04-02', groupId: 'CAL-04', subject: 'calculus1', label: '곱 또는 합으로 표현된 함수의 연속', plain: '곱 또는 합으로 표현된 함수의 연속', hwp: '곱 또는 합으로 표현된 함수의 연속' },
  { id: 'CAL-04-03', groupId: 'CAL-04', subject: 'calculus1', label: '함수의 연속과 불연속(3) : 그래프가 주어진 경우', plain: '함수의 연속과 불연속(3) : 그래프가 주어진 경우', hwp: '함수의 연속과 불연속(3) : 그래프가 주어진 경우' },
  { id: 'CAL-04-04', groupId: 'CAL-04', subject: 'calculus1', label: '함수의 연속과 불연속(4) : 합성함수의 연속', plain: '함수의 연속과 불연속(4) : 합성함수의 연속', hwp: '함수의 연속과 불연속(4) : 합성함수의 연속' },
  { id: 'CAL-04-05', groupId: 'CAL-04', subject: 'calculus1', label: '함수의 연속과 불연속(5) : 가우스 기호를 포함한 함수', plain: '함수의 연속과 불연속(5) : 가우스 기호를 포함한 함수', hwp: '함수의 연속과 불연속(5) : 가우스 기호를 포함한 함수' },
  { id: 'CAL-04-06', groupId: 'CAL-04', subject: 'calculus1', label: '함수의 연속과 불연속(6) : $(x-a)f(x)$꼴의 함수', plain: '함수의 연속과 불연속(6) : (x-a)f(x)꼴의 함수', hwp: '함수의 연속과 불연속(6) : $(x-a)f(x)`$꼴의 함수' },
  { id: 'CAL-04-07', groupId: 'CAL-04', subject: 'calculus1', label: '함수의 연속과 불연속(7) : $f(x)=f(x+k)$꼴의 함수', plain: '함수의 연속과 불연속(7) : f(x)=f(x+k)꼴의 함수', hwp: '함수의 연속과 불연속(7) : $f(x)=f(x+k)`$꼴의 함수' },
  { id: 'CAL-04-08', groupId: 'CAL-04', subject: 'calculus1', label: '함수가 연속일 조건(2) : 다양한 형태의 함수가 연속일 조건', plain: '함수가 연속일 조건(2) : 다양한 형태의 함수가 연속일 조건', hwp: '함수가 연속일 조건(2) : 다양한 형태의 함수가 연속일 조건' },
  { id: 'CAL-04-09', groupId: 'CAL-04', subject: 'calculus1', label: '함수가 불연속일 조건(2) : 다양한 형태의 함수가 불연속일 조건', plain: '함수가 불연속일 조건(2) : 다양한 형태의 함수가 불연속일 조건', hwp: '함수가 불연속일 조건(2) : 다양한 형태의 함수가 불연속일 조건' },
  { id: 'CAL-04-10', groupId: 'CAL-04', subject: 'calculus1', label: '최대 · 최소 정리', plain: '최대 · 최소 정리', hwp: '최대 · 최소 정리' },
  { id: 'CAL-04-11', groupId: 'CAL-04', subject: 'calculus1', label: '사잇값의 정리', plain: '사잇값의 정리', hwp: '사잇값의 정리' },
  { id: 'CAL-04-12', groupId: 'CAL-04', subject: 'calculus1', label: '사잇값의 정리의 활용(1) : 실근이 존재하는 구간', plain: '사잇값의 정리의 활용(1) : 실근이 존재하는 구간', hwp: '사잇값의 정리의 활용(1) : 실근이 존재하는 구간' },
  { id: 'CAL-04-13', groupId: 'CAL-04', subject: 'calculus1', label: '사잇값의 정리의 활용(2) : 실근의 개수', plain: '사잇값의 정리의 활용(2) : 실근의 개수', hwp: '사잇값의 정리의 활용(2) : 실근의 개수' },
  { id: 'CAL-04-14', groupId: 'CAL-04', subject: 'calculus1', label: '사잇값의 정리의 활용(3) : 실생활에서의 활용', plain: '사잇값의 정리의 활용(3) : 실생활에서의 활용', hwp: '사잇값의 정리의 활용(3) : 실생활에서의 활용' },
  { id: 'CAL-04-15', groupId: 'CAL-04', subject: 'calculus1', label: '사잇값의 정리의 활용(4) : 기타', plain: '사잇값의 정리의 활용(4) : 기타', hwp: '사잇값의 정리의 활용(4) : 기타' },
  { id: 'CAL-05-01', groupId: 'CAL-05', subject: 'calculus1', label: '평균변화율', plain: '평균변화율', hwp: '평균변화율' },
  { id: 'CAL-05-02', groupId: 'CAL-05', subject: 'calculus1', label: '평균변화율과 미분계수', plain: '평균변화율과 미분계수', hwp: '평균변화율과 미분계수' },
  { id: 'CAL-05-03', groupId: 'CAL-05', subject: 'calculus1', label: '평균변화율의 기하학적 의미', plain: '평균변화율의 기하학적 의미', hwp: '평균변화율의 기하학적 의미' },
  { id: 'CAL-05-04', groupId: 'CAL-05', subject: 'calculus1', label: '미분계수의 정의를 이용한 미분계수의 표현', plain: '미분계수의 정의를 이용한 미분계수의 표현', hwp: '미분계수의 정의를 이용한 미분계수의 표현' },
  { id: 'CAL-05-05', groupId: 'CAL-05', subject: 'calculus1', label: '미분계수를 이용한 극한값의 계산(1) : $\\frac{f(a+h)-f(a)}{h}$ 꼴의 극한', plain: '미분계수를 이용한 극한값의 계산(1) : \\frac{f(a+h)-f(a)}{h} 꼴의 극한', hwp: '미분계수를 이용한 극한값의 계산(1) : ${f(a+h)-f(a)} overh`$ 꼴의 극한' },
  { id: 'CAL-05-06', groupId: 'CAL-05', subject: 'calculus1', label: '미분계수를 이용한 극한값의 계산(2) : $\\frac{f(x)-f(a)}{x-a}$꼴의 극한', plain: '미분계수를 이용한 극한값의 계산(2) : \\frac{f(x)-f(a)}{x-a}꼴의 극한', hwp: '미분계수를 이용한 극한값의 계산(2) : ${f(x)- f(a)} overx-a`$꼴의 극한' },
  { id: 'CAL-05-07', groupId: 'CAL-05', subject: 'calculus1', label: '미분계수를 이용한 극한값의 계산(3) : $\\lim_{n\\to\\infty} n\\left\\{f\\left(a+\\frac{1}{n}\\right)-f(a)\\right\\}$ 꼴의 변형', plain: '미분계수를 이용한 극한값의 계산(3) : \\lim_{n\\to\\infty} n\\left\\{f\\left(a+\\frac{1}{n}\\right)-f(a)\\right\\} 꼴의 변형', hwp: '미분계수를 이용한 극한값의 계산(3) : $lim _{n `rarrow`  INF } {n LEFT { f LEFT ( a+ {1} over {n} RIGHT ) -f(a) RIGHT } `}$ 꼴의 변형' },
  { id: 'CAL-05-08', groupId: 'CAL-05', subject: 'calculus1', label: '관계식이 주어질 때 미분계수 구하기', plain: '관계식이 주어질 때 미분계수 구하기', hwp: '관계식이 주어질 때 미분계수 구하기' },
  { id: 'CAL-05-09', groupId: 'CAL-05', subject: 'calculus1', label: '미분계수의 기하적 의미', plain: '미분계수의 기하적 의미', hwp: '미분계수의 기하적 의미' },
  { id: 'CAL-05-10', groupId: 'CAL-05', subject: 'calculus1', label: '접선의 기울기를 이용하여 미분계수 구하기', plain: '접선의 기울기를 이용하여 미분계수 구하기', hwp: '접선의 기울기를 이용하여 미분계수 구하기' },
  { id: 'CAL-05-11', groupId: 'CAL-05', subject: 'calculus1', label: '미분가능성과 연속성(1) : 정의를 이용하는 경우', plain: '미분가능성과 연속성(1) : 정의를 이용하는 경우', hwp: '미분가능성과 연속성(1) : 정의를 이용하는 경우' },
  { id: 'CAL-05-12', groupId: 'CAL-05', subject: 'calculus1', label: '미분가능성과 연속성(2) : 그래프가 주어진 경우', plain: '미분가능성과 연속성(2) : 그래프가 주어진 경우', hwp: '미분가능성과 연속성(2) : 그래프가 주어진 경우' },
  { id: 'CAL-05-13', groupId: 'CAL-05', subject: 'calculus1', label: '미분가능성과 연속성(3) : 구간에 따라 다르게 정의된 함수', plain: '미분가능성과 연속성(3) : 구간에 따라 다르게 정의된 함수', hwp: '미분가능성과 연속성(3) : 구간에 따라 다르게 정의된 함수' },
  { id: 'CAL-06-01', groupId: 'CAL-06', subject: 'calculus1', label: '도함수의 정의', plain: '도함수의 정의', hwp: '도함수의 정의' },
  { id: 'CAL-06-02', groupId: 'CAL-06', subject: 'calculus1', label: '도함수의 정의를 이용하여 도함수 구하기', plain: '도함수의 정의를 이용하여 도함수 구하기', hwp: '도함수의 정의를 이용하여 도함수 구하기' },
  { id: 'CAL-06-03', groupId: 'CAL-06', subject: 'calculus1', label: '관계식이 주어질 때 도함수 구하기', plain: '관계식이 주어질 때 도함수 구하기', hwp: '관계식이 주어질 때 도함수 구하기' },
  { id: 'CAL-06-04', groupId: 'CAL-06', subject: 'calculus1', label: '미분법의 공식', plain: '미분법의 공식', hwp: '미분법의 공식' },
  { id: 'CAL-06-05', groupId: 'CAL-06', subject: 'calculus1', label: '미분법과 미정계수의 결정', plain: '미분법과 미정계수의 결정', hwp: '미분법과 미정계수의 결정' },
  { id: 'CAL-06-06', groupId: 'CAL-06', subject: 'calculus1', label: '미분계수를 포함한 함수의 미분계수의 표현', plain: '미분계수를 포함한 함수의 미분계수의 표현', hwp: '미분계수를 포함한 함수의 미분계수의 표현' },
  { id: 'CAL-06-07', groupId: 'CAL-06', subject: 'calculus1', label: '곱의 미분법(1) : $y=f(x)g(x)$꼴', plain: '곱의 미분법(1) : y=f(x)g(x)꼴', hwp: '곱의 미분법(1) : $y=f(x)g(x)`$꼴' },
  { id: 'CAL-06-08', groupId: 'CAL-06', subject: 'calculus1', label: '곱의 미분법(2) : $y=\\left\\{f(x)\\right\\}^{n}$꼴', plain: '곱의 미분법(2) : y=\\left\\{f(x)\\right\\}^{n}꼴', hwp: '곱의 미분법(2) : $y=left{f(x)right}^n`$꼴' },
  { id: 'CAL-06-09', groupId: 'CAL-06', subject: 'calculus1', label: '미분법의 공식 : 종합', plain: '미분법의 공식 : 종합', hwp: '미분법의 공식 : 종합' },
  { id: 'CAL-06-10', groupId: 'CAL-06', subject: 'calculus1', label: '미분계수를 이용한 미정계수의 결정', plain: '미분계수를 이용한 미정계수의 결정', hwp: '미분계수를 이용한 미정계수의 결정' },
  { id: 'CAL-06-11', groupId: 'CAL-06', subject: 'calculus1', label: '미분계수를 이용하여 극한값 구하기', plain: '미분계수를 이용하여 극한값 구하기', hwp: '미분계수를 이용하여 극한값 구하기' },
  { id: 'CAL-06-12', groupId: 'CAL-06', subject: 'calculus1', label: '치환을 이용한 극한값의 계산', plain: '치환을 이용한 극한값의 계산', hwp: '치환을 이용한 극한값의 계산' },
  { id: 'CAL-06-13', groupId: 'CAL-06', subject: 'calculus1', label: '접선의 기울기를 이용한 미정계수의 결정', plain: '접선의 기울기를 이용한 미정계수의 결정', hwp: '접선의 기울기를 이용한 미정계수의 결정' },
  { id: 'CAL-06-14', groupId: 'CAL-06', subject: 'calculus1', label: '미분의 항등식에의 활용', plain: '미분의 항등식에의 활용', hwp: '미분의 항등식에의 활용' },
  { id: 'CAL-06-15', groupId: 'CAL-06', subject: 'calculus1', label: '다항식의 나눗셈에서 미분법의 활용(1) : 나누어떨어지는 경우', plain: '다항식의 나눗셈에서 미분법의 활용(1) : 나누어떨어지는 경우', hwp: '다항식의 나눗셈에서 미분법의 활용(1) : 나누어떨어지는 경우' },
  { id: 'CAL-06-16', groupId: 'CAL-06', subject: 'calculus1', label: '다항식의 나눗셈에서 미분법의 활용(2) : 나누어떨어지지 않는 경우', plain: '다항식의 나눗셈에서 미분법의 활용(2) : 나누어떨어지지 않는 경우', hwp: '다항식의 나눗셈에서 미분법의 활용(2) : 나누어떨어지지 않는 경우' },
  { id: 'CAL-07-01', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 기울기', plain: '접선의 기울기', hwp: '접선의 기울기' },
  { id: 'CAL-07-02', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식 구하기(1) : 접점의 좌표가 주어진 경우', plain: '접선의 방정식 구하기(1) : 접점의 좌표가 주어진 경우', hwp: '접선의 방정식 구하기(1) : 접점의 좌표가 주어진 경우' },
  { id: 'CAL-07-03', groupId: 'CAL-07', subject: 'calculus1', label: '곡선 위의 점에서의 접선의 방정식의 활용', plain: '곡선 위의 점에서의 접선의 방정식의 활용', hwp: '곡선 위의 점에서의 접선의 방정식의 활용' },
  { id: 'CAL-07-04', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식 구하기(2) : 접선과 수직인 경우', plain: '접선의 방정식 구하기(2) : 접선과 수직인 경우', hwp: '접선의 방정식 구하기(2) : 접선과 수직인 경우' },
  { id: 'CAL-07-05', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식 구하기(3) : 기울기가 주어진 경우', plain: '접선의 방정식 구하기(3) : 기울기가 주어진 경우', hwp: '접선의 방정식 구하기(3) : 기울기가 주어진 경우' },
  { id: 'CAL-07-06', groupId: 'CAL-07', subject: 'calculus1', label: '기울기가 주어진 접선의 방정식의 활용', plain: '기울기가 주어진 접선의 방정식의 활용', hwp: '기울기가 주어진 접선의 방정식의 활용' },
  { id: 'CAL-07-07', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식 구하기(4) : 기울기가 주어지지 않은 경우', plain: '접선의 방정식 구하기(4) : 기울기가 주어지지 않은 경우', hwp: '접선의 방정식 구하기(4) : 기울기가 주어지지 않은 경우' },
  { id: 'CAL-07-08', groupId: 'CAL-07', subject: 'calculus1', label: '곡선과 접선의 교점', plain: '곡선과 접선의 교점', hwp: '곡선과 접선의 교점' },
  { id: 'CAL-07-09', groupId: 'CAL-07', subject: 'calculus1', label: '곡선과 직선이 접할 때 미정계수 구하기', plain: '곡선과 직선이 접할 때 미정계수 구하기', hwp: '곡선과 직선이 접할 때 미정계수 구하기' },
  { id: 'CAL-07-10', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 기울기의 최댓값 또는 최솟값', plain: '접선의 기울기의 최댓값 또는 최솟값', hwp: '접선의 기울기의 최댓값 또는 최솟값' },
  { id: 'CAL-07-11', groupId: 'CAL-07', subject: 'calculus1', label: '곡선 위의 점과 직선 사이의 거리', plain: '곡선 위의 점과 직선 사이의 거리', hwp: '곡선 위의 점과 직선 사이의 거리' },
  { id: 'CAL-07-12', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식 구하기(5) : 곡선 밖의 한 점이 주어진 경우', plain: '접선의 방정식 구하기(5) : 곡선 밖의 한 점이 주어진 경우', hwp: '접선의 방정식 구하기(5) : 곡선 밖의 한 점이 주어진 경우' },
  { id: 'CAL-07-13', groupId: 'CAL-07', subject: 'calculus1', label: '곡선 밖의 한 점에서 그은 접선의 개수', plain: '곡선 밖의 한 점에서 그은 접선의 개수', hwp: '곡선 밖의 한 점에서 그은 접선의 개수' },
  { id: 'CAL-07-14', groupId: 'CAL-07', subject: 'calculus1', label: '곡선 밖의 한 점에서 곡선에 그은 접선의 방정식의 활용', plain: '곡선 밖의 한 점에서 곡선에 그은 접선의 방정식의 활용', hwp: '곡선 밖의 한 점에서 곡선에 그은 접선의 방정식의 활용' },
  { id: 'CAL-07-15', groupId: 'CAL-07', subject: 'calculus1', label: '공통인 접선', plain: '공통인 접선', hwp: '공통인 접선' },
  { id: 'CAL-07-16', groupId: 'CAL-07', subject: 'calculus1', label: '접선과 좌표축으로 둘러싸인 도형의 넓이', plain: '접선과 좌표축으로 둘러싸인 도형의 넓이', hwp: '접선과 좌표축으로 둘러싸인 도형의 넓이' },
  { id: 'CAL-07-17', groupId: 'CAL-07', subject: 'calculus1', label: '곡선과 원의 접선', plain: '곡선과 원의 접선', hwp: '곡선과 원의 접선' },
  { id: 'CAL-07-18', groupId: 'CAL-07', subject: 'calculus1', label: '접선의 방정식의 활용', plain: '접선의 방정식의 활용', hwp: '접선의 방정식의 활용' },
  { id: 'CAL-08-01', groupId: 'CAL-08', subject: 'calculus1', label: '롤의 정리', plain: '롤의 정리', hwp: '롤의 정리' },
  { id: 'CAL-08-02', groupId: 'CAL-08', subject: 'calculus1', label: '평균값 정리', plain: '평균값 정리', hwp: '평균값 정리' },
  { id: 'CAL-08-03', groupId: 'CAL-08', subject: 'calculus1', label: '평균값 정리를 만족시키는 상수의 개수', plain: '평균값 정리를 만족시키는 상수의 개수', hwp: '평균값 정리를 만족시키는 상수의 개수' },
  { id: 'CAL-08-04', groupId: 'CAL-08', subject: 'calculus1', label: '평균값 정리의 활용', plain: '평균값 정리의 활용', hwp: '평균값 정리의 활용' },
  { id: 'CAL-08-05', groupId: 'CAL-08', subject: 'calculus1', label: '평균값 정리의 변형', plain: '평균값 정리의 변형', hwp: '평균값 정리의 변형' },
  { id: 'CAL-09-01', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 증가와 감소', plain: '함수의 증가와 감소', hwp: '함수의 증가와 감소' },
  { id: 'CAL-09-02', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 그래프와 증가 · 감소', plain: '함수의 그래프와 증가 · 감소', hwp: '함수의 그래프와 증가 · 감소' },
  { id: 'CAL-09-03', groupId: 'CAL-09', subject: 'calculus1', label: '삼차함수의 증가 · 감소의 조건(1) : 실수 전체의 구간에서', plain: '삼차함수의 증가 · 감소의 조건(1) : 실수 전체의 구간에서', hwp: '삼차함수의 증가 · 감소의 조건(1) : 실수 전체의 구간에서' },
  { id: 'CAL-09-04', groupId: 'CAL-09', subject: 'calculus1', label: '삼차함수의 증가 · 감소의 조건(2) : 주어진 구간에서', plain: '삼차함수의 증가 · 감소의 조건(2) : 주어진 구간에서', hwp: '삼차함수의 증가 · 감소의 조건(2) : 주어진 구간에서' },
  { id: 'CAL-09-05', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 극대 · 극소 (함수의 극값, 극댓값, 극솟값 구하기)', plain: '함수의 극대 · 극소 (함수의 극값, 극댓값, 극솟값 구하기)', hwp: '함수의 극대 · 극소 (함수의 극값, 극댓값, 극솟값 구하기)' },
  { id: 'CAL-09-06', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 극대 · 극소를 이용한 미정계수의 결정', plain: '함수의 극대 · 극소를 이용한 미정계수의 결정', hwp: '함수의 극대 · 극소를 이용한 미정계수의 결정' },
  { id: 'CAL-09-07', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 극대 · 극소의 활용', plain: '함수의 극대 · 극소의 활용', hwp: '함수의 극대 · 극소의 활용' },
  { id: 'CAL-09-08', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 극대 · 극소를 이용한 계수의 부호 결정(1) : 삼차함수', plain: '함수의 극대 · 극소를 이용한 계수의 부호 결정(1) : 삼차함수', hwp: '함수의 극대 · 극소를 이용한 계수의 부호 결정(1) : 삼차함수' },
  { id: 'CAL-09-09', groupId: 'CAL-09', subject: 'calculus1', label: '함수의 극대 · 극소를 이용한 계수의 부호 결정(2) : 사차함수', plain: '함수의 극대 · 극소를 이용한 계수의 부호 결정(2) : 사차함수', hwp: '함수의 극대 · 극소를 이용한 계수의 부호 결정(2) : 사차함수' },
  { id: 'CAL-09-10', groupId: 'CAL-09', subject: 'calculus1', label: '도함수의 그래프와 증가 · 감소', plain: '도함수의 그래프와 증가 · 감소', hwp: '도함수의 그래프와 증가 · 감소' },
  { id: 'CAL-10-01', groupId: 'CAL-10', subject: 'calculus1', label: '함수의 그래프 그리기', plain: '함수의 그래프 그리기', hwp: '함수의 그래프 그리기' },
  { id: 'CAL-10-02', groupId: 'CAL-10', subject: 'calculus1', label: '도함수 $y=f\'(x)$의 그래프와 함수의 극값', plain: '도함수 y=f\'(x)의 그래프와 함수의 극값', hwp: '도함수 $y=f`\'(x)`$의 그래프와 함수의 극값' },
  { id: 'CAL-10-03', groupId: 'CAL-10', subject: 'calculus1', label: '함수 $y=f\'(x)$의 그래프의 해석', plain: '함수 y=f\'(x)의 그래프의 해석', hwp: '함수 $y=f`\'(x)`$의 그래프의 해석' },
  { id: 'CAL-10-04', groupId: 'CAL-10', subject: 'calculus1', label: '삼차함수의 극값(1) : 전체 구간에서 삼차함수가 극값을 가질 조건', plain: '삼차함수의 극값(1) : 전체 구간에서 삼차함수가 극값을 가질 조건', hwp: '삼차함수의 극값(1) : 전체 구간에서 삼차함수가 극값을 가질 조건' },
  { id: 'CAL-10-05', groupId: 'CAL-10', subject: 'calculus1', label: '삼차함수의 극값(2) : 전체 구간에서 삼차함수가 극값을 갖지 않을 조건', plain: '삼차함수의 극값(2) : 전체 구간에서 삼차함수가 극값을 갖지 않을 조건', hwp: '삼차함수의 극값(2) : 전체 구간에서 삼차함수가 극값을 갖지 않을 조건' },
  { id: 'CAL-10-06', groupId: 'CAL-10', subject: 'calculus1', label: '삼차함수의 극값(3) : 주어진 구간에서 삼차함수가 극값을 가질 조건', plain: '삼차함수의 극값(3) : 주어진 구간에서 삼차함수가 극값을 가질 조건', hwp: '삼차함수의 극값(3) : 주어진 구간에서 삼차함수가 극값을 가질 조건' },
  { id: 'CAL-10-07', groupId: 'CAL-10', subject: 'calculus1', label: '삼차함수의 극값(4) : 주어진 구간에서 삼차함수가 극값을 갖지 않을 조건', plain: '삼차함수의 극값(4) : 주어진 구간에서 삼차함수가 극값을 갖지 않을 조건', hwp: '삼차함수의 극값(4) : 주어진 구간에서 삼차함수가 극값을 갖지 않을 조건' },
  { id: 'CAL-10-08', groupId: 'CAL-10', subject: 'calculus1', label: '사차함수의 극값(1) : 전체 구간에서 사차함수가 극값을 가질 조건', plain: '사차함수의 극값(1) : 전체 구간에서 사차함수가 극값을 가질 조건', hwp: '사차함수의 극값(1) : 전체 구간에서 사차함수가 극값을 가질 조건' },
  { id: 'CAL-10-09', groupId: 'CAL-10', subject: 'calculus1', label: '사차함수의 극값(2) : 전체 구간에서 사차함수가 극값을 갖지 않을 조건', plain: '사차함수의 극값(2) : 전체 구간에서 사차함수가 극값을 갖지 않을 조건', hwp: '사차함수의 극값(2) : 전체 구간에서 사차함수가 극값을 갖지 않을 조건' },
  { id: 'CAL-10-10', groupId: 'CAL-10', subject: 'calculus1', label: '함수의 최대 · 최소 (함수의 최댓값, 최솟값 구하기)', plain: '함수의 최대 · 최소 (함수의 최댓값, 최솟값 구하기)', hwp: '함수의 최대 · 최소 (함수의 최댓값, 최솟값 구하기)' },
  { id: 'CAL-10-11', groupId: 'CAL-10', subject: 'calculus1', label: '함수의 최대 · 최소를 이용한 미정계수의 결정', plain: '함수의 최대 · 최소를 이용한 미정계수의 결정', hwp: '함수의 최대 · 최소를 이용한 미정계수의 결정' },
  { id: 'CAL-10-12', groupId: 'CAL-10', subject: 'calculus1', label: '최대 · 최소의 활용(1) : 길이', plain: '최대 · 최소의 활용(1) : 길이', hwp: '최대 · 최소의 활용(1) : 길이' },
  { id: 'CAL-10-13', groupId: 'CAL-10', subject: 'calculus1', label: '최대 · 최소의 활용(2) : 넓이', plain: '최대 · 최소의 활용(2) : 넓이', hwp: '최대 · 최소의 활용(2) : 넓이' },
  { id: 'CAL-10-14', groupId: 'CAL-10', subject: 'calculus1', label: '최대 · 최소의 활용(3) : 부피', plain: '최대 · 최소의 활용(3) : 부피', hwp: '최대 · 최소의 활용(3) : 부피' },
  { id: 'CAL-10-15', groupId: 'CAL-10', subject: 'calculus1', label: '최대 · 최소의 활용(4) : 이외의 경우', plain: '최대 · 최소의 활용(4) : 이외의 경우', hwp: '최대 · 최소의 활용(4) : 이외의 경우' },
  { id: 'CAL-11-01', groupId: 'CAL-11', subject: 'calculus1', label: '방정식 $f(x)=0$의 실근', plain: '방정식 f(x)=0의 실근', hwp: '방정식 $f(x)=0`$의 실근' },
  { id: 'CAL-11-02', groupId: 'CAL-11', subject: 'calculus1', label: '방정식 $f(x)=k$의 실근의 개수', plain: '방정식 f(x)=k의 실근의 개수', hwp: '방정식 $f(x)=k`$의 실근의 개수' },
  { id: 'CAL-11-03', groupId: 'CAL-11', subject: 'calculus1', label: '방정식 $f(x)=k$의 실근의 부호', plain: '방정식 f(x)=k의 실근의 부호', hwp: '방정식 $f(x)=k`$의 실근의 부호' },
  { id: 'CAL-11-04', groupId: 'CAL-11', subject: 'calculus1', label: '방정식 $f(x)=g(x)$의 실근', plain: '방정식 f(x)=g(x)의 실근', hwp: '방정식 $f(x)=g(x)`$의 실근' },
  { id: 'CAL-11-05', groupId: 'CAL-11', subject: 'calculus1', label: '근의 판별(1) : 삼차방정식의 근의 판별', plain: '근의 판별(1) : 삼차방정식의 근의 판별', hwp: '근의 판별(1) : 삼차방정식의 근의 판별' },
  { id: 'CAL-11-06', groupId: 'CAL-11', subject: 'calculus1', label: '근의 판별(2) : 사차방정식의 근의 판별', plain: '근의 판별(2) : 사차방정식의 근의 판별', hwp: '근의 판별(2) : 사차방정식의 근의 판별' },
  { id: 'CAL-11-07', groupId: 'CAL-11', subject: 'calculus1', label: '두 그래프의 교점의 개수', plain: '두 그래프의 교점의 개수', hwp: '두 그래프의 교점의 개수' },
  { id: 'CAL-11-08', groupId: 'CAL-11', subject: 'calculus1', label: '접선의 개수', plain: '접선의 개수', hwp: '접선의 개수' },
  { id: 'CAL-11-09', groupId: 'CAL-11', subject: 'calculus1', label: '주어진 구간에서 부등식이 항상 성립할 조건(1) : 증가 · 감소의 활용', plain: '주어진 구간에서 부등식이 항상 성립할 조건(1) : 증가 · 감소의 활용', hwp: '주어진 구간에서 부등식이 항상 성립할 조건(1) : 증가 · 감소의 활용' },
  { id: 'CAL-11-10', groupId: 'CAL-11', subject: 'calculus1', label: '주어진 구간에서 부등식이 항상 성립할 조건(2) : 최대 · 최소의 활용', plain: '주어진 구간에서 부등식이 항상 성립할 조건(2) : 최대 · 최소의 활용', hwp: '주어진 구간에서 부등식이 항상 성립할 조건(2) : 최대 · 최소의 활용' },
  { id: 'CAL-11-11', groupId: 'CAL-11', subject: 'calculus1', label: '부등식이 항상 성립할 조건', plain: '부등식이 항상 성립할 조건', hwp: '부등식이 항상 성립할 조건' },
  { id: 'CAL-11-12', groupId: 'CAL-11', subject: 'calculus1', label: '모든 실수 $x$에 대하여 부등식 $f(x)\\geq 0$이 성립함을 증명하기', plain: '모든 실수 x에 대하여 부등식 f(x)\\geq 0이 성립함을 증명하기', hwp: '모든 실수 $x`$에 대하여 부등식 $f(x) >=0`$이 성립함을 증명하기' },
  { id: 'CAL-11-13', groupId: 'CAL-11', subject: 'calculus1', label: '주어진 구간에서 부등식 $f(x)\\geq 0$이 성립함을 증명하기', plain: '주어진 구간에서 부등식 f(x)\\geq 0이 성립함을 증명하기', hwp: '주어진 구간에서 부등식 $f(x) >=0`$이 성립함을 증명하기' },
  { id: 'CAL-11-14', groupId: 'CAL-11', subject: 'calculus1', label: '부등식 $f(x)>g(x)$꼴이 성립함을 증명하기', plain: '부등식 f(x)>g(x)꼴이 성립함을 증명하기', hwp: '부등식 $f(x) > g(x)`$꼴이 성립함을 증명하기' },
  { id: 'CAL-12-01', groupId: 'CAL-12', subject: 'calculus1', label: '속도', plain: '속도', hwp: '속도' },
  { id: 'CAL-12-02', groupId: 'CAL-12', subject: 'calculus1', label: '가속도', plain: '가속도', hwp: '가속도' },
  { id: 'CAL-12-03', groupId: 'CAL-12', subject: 'calculus1', label: '속력의 최댓값', plain: '속력의 최댓값', hwp: '속력의 최댓값' },
  { id: 'CAL-12-04', groupId: 'CAL-12', subject: 'calculus1', label: '속도 · 가속도와 운동 방향', plain: '속도 · 가속도와 운동 방향', hwp: '속도 · 가속도와 운동 방향' },
  { id: 'CAL-12-05', groupId: 'CAL-12', subject: 'calculus1', label: '정지하는 물체의 속도와 움직인 거리', plain: '정지하는 물체의 속도와 움직인 거리', hwp: '정지하는 물체의 속도와 움직인 거리' },
  { id: 'CAL-12-06', groupId: 'CAL-12', subject: 'calculus1', label: '위로 던진 물체의 위치와 속도', plain: '위로 던진 물체의 위치와 속도', hwp: '위로 던진 물체의 위치와 속도' },
  { id: 'CAL-12-07', groupId: 'CAL-12', subject: 'calculus1', label: '그래프의 해석(1) : 속도', plain: '그래프의 해석(1) : 속도', hwp: '그래프의 해석(1) : 속도' },
  { id: 'CAL-12-08', groupId: 'CAL-12', subject: 'calculus1', label: '그래프의 해석(2) : 위치', plain: '그래프의 해석(2) : 위치', hwp: '그래프의 해석(2) : 위치' },
  { id: 'CAL-12-09', groupId: 'CAL-12', subject: 'calculus1', label: '시각에 대한 변화율(1)  길이', plain: '시각에 대한 변화율(1) 길이', hwp: '시각에 대한 변화율(1)  길이' },
  { id: 'CAL-12-10', groupId: 'CAL-12', subject: 'calculus1', label: '시각에 대한 변화율(2)  넓이', plain: '시각에 대한 변화율(2) 넓이', hwp: '시각에 대한 변화율(2)  넓이' },
  { id: 'CAL-12-11', groupId: 'CAL-12', subject: 'calculus1', label: '시각에 대한 변화율(3)  부피', plain: '시각에 대한 변화율(3) 부피', hwp: '시각에 대한 변화율(3)  부피' },
  { id: 'CAL-13-01', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 정의', plain: '부정적분의 정의', hwp: '부정적분의 정의' },
  { id: 'CAL-13-02', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 미분의 관계(1): $\\frac{d}{dx}\\int f(x)\\,dx=f(x)$', plain: '부정적분과 미분의 관계(1): \\frac{d}{dx}\\int f(x)\\,dx=f(x)', hwp: '부정적분과 미분의 관계(1): $d overdx int{f(x)`dx =f(x)`$' },
  { id: 'CAL-13-03', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 미분의 관계(2): $\\int \\frac{d}{dx}f(x)\\,dx=f(x)+C$', plain: '부정적분과 미분의 관계(2): \\int \\frac{d}{dx}f(x)\\,dx=f(x)+C', hwp: '부정적분과 미분의 관계(2): $int {d over dx f(x)}`dx =f(x)+C`$' },
  { id: 'CAL-13-04', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 미분의 관계를 이용하여 함수 구하기', plain: '부정적분과 미분의 관계를 이용하여 함수 구하기', hwp: '부정적분과 미분의 관계를 이용하여 함수 구하기' },
  { id: 'CAL-13-05', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산', plain: '부정적분의 계산', hwp: '부정적분의 계산' },
  { id: 'CAL-13-06', groupId: 'CAL-13', subject: 'calculus1', label: '도함수가 주어진 경우의 부정적분 : $f\'(x)$로부터 $f(x)$구하기', plain: '도함수가 주어진 경우의 부정적분 : f\'(x)로부터 f(x)구하기', hwp: '도함수가 주어진 경우의 부정적분 : $f`\'(x)`$로부터 $f(x)`$구하기' },
  { id: 'CAL-13-07', groupId: 'CAL-13', subject: 'calculus1', label: '도함수가 주어진 경우의 부정적분(2) : 도함수의 그래프가 주어진 경우', plain: '도함수가 주어진 경우의 부정적분(2) : 도함수의 그래프가 주어진 경우', hwp: '도함수가 주어진 경우의 부정적분(2) : 도함수의 그래프가 주어진 경우' },
  { id: 'CAL-13-08', groupId: 'CAL-13', subject: 'calculus1', label: '$f(x)$와 그 부정적분 $F(x)$의 관계', plain: 'f(x)와 그 부정적분 F(x)의 관계', hwp: '$f(x)`$와 그 부정적분 $F(x)`$의 관계' },
  { id: 'CAL-13-09', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 미분의 관계의 활용 : $xf(x)$꼴을 포함하는 경우', plain: '부정적분과 미분의 관계의 활용 : xf(x)꼴을 포함하는 경우', hwp: '부정적분과 미분의 관계의 활용 : $xf(x)`$꼴을 포함하는 경우' },
  { id: 'CAL-13-10', groupId: 'CAL-13', subject: 'calculus1', label: '함수의 연속과 부정적분', plain: '함수의 연속과 부정적분', hwp: '함수의 연속과 부정적분' },
  { id: 'CAL-13-11', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(1) : 다항함수가 주어진 경우', plain: '부정적분의 계산(1) : 다항함수가 주어진 경우', hwp: '부정적분의 계산(1) : 다항함수가 주어진 경우' },
  { id: 'CAL-13-12', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(2) : 기울기가 주어진 경우', plain: '부정적분의 계산(2) : 기울기가 주어진 경우', hwp: '부정적분의 계산(2) : 기울기가 주어진 경우' },
  { id: 'CAL-13-13', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(3) : 미분계수가 주어진 경우', plain: '부정적분의 계산(3) : 미분계수가 주어진 경우', hwp: '부정적분의 계산(3) : 미분계수가 주어진 경우' },
  { id: 'CAL-13-14', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(4) : 극값이 주어진 경우', plain: '부정적분의 계산(4) : 극값이 주어진 경우', hwp: '부정적분의 계산(4) : 극값이 주어진 경우' },
  { id: 'CAL-13-15', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(5) : 합 또는 곱으로 주어진 함수', plain: '부정적분의 계산(5) : 합 또는 곱으로 주어진 함수', hwp: '부정적분의 계산(5) : 합 또는 곱으로 주어진 함수' },
  { id: 'CAL-13-16', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(6) : 도함수의 정의를 이용', plain: '부정적분의 계산(6) : 도함수의 정의를 이용', hwp: '부정적분의 계산(6) : 도함수의 정의를 이용' },
  { id: 'CAL-13-17', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 계산(7) : 유리함수가 주어진 경우', plain: '부정적분의 계산(7) : 유리함수가 주어진 경우', hwp: '부정적분의 계산(7) : 유리함수가 주어진 경우' },
  { id: 'CAL-13-18', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 절대부등식', plain: '부정적분과 절대부등식', hwp: '부정적분과 절대부등식' },
  { id: 'CAL-13-19', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 미분계수를 이용한 극한값의 계산', plain: '부정적분과 미분계수를 이용한 극한값의 계산', hwp: '부정적분과 미분계수를 이용한 극한값의 계산' },
  { id: 'CAL-13-20', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분과 극대 · 극소', plain: '부정적분과 극대 · 극소', hwp: '부정적분과 극대 · 극소' },
  { id: 'CAL-13-21', groupId: 'CAL-13', subject: 'calculus1', label: '부정적분의 활용', plain: '부정적분의 활용', hwp: '부정적분의 활용' },
  { id: 'CAL-14-01', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 정의', plain: '정적분의 정의', hwp: '정적분의 정의' },
  { id: 'CAL-14-02', groupId: 'CAL-14', subject: 'calculus1', label: '적분과 미분의 관계', plain: '적분과 미분의 관계', hwp: '적분과 미분의 관계' },
  { id: 'CAL-14-03', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 정의의 활용', plain: '정적분의 정의의 활용', hwp: '정적분의 정의의 활용' },
  { id: 'CAL-14-04', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산', plain: '정적분의 계산', hwp: '정적분의 계산' },
  { id: 'CAL-14-05', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산(1) : 적분 구간이 같은 경우', plain: '정적분의 계산(1) : 적분 구간이 같은 경우', hwp: '정적분의 계산(1) : 적분 구간이 같은 경우' },
  { id: 'CAL-14-06', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산(2) : 피적분함수가 같은 경우', plain: '정적분의 계산(2) : 피적분함수가 같은 경우', hwp: '정적분의 계산(2) : 피적분함수가 같은 경우' },
  { id: 'CAL-14-07', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산(3) : 구간에 따라 다르게 정의된 함수', plain: '정적분의 계산(3) : 구간에 따라 다르게 정의된 함수', hwp: '정적분의 계산(3) : 구간에 따라 다르게 정의된 함수' },
  { id: 'CAL-14-08', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산(4) : 절댓값 기호를 포함한 함수', plain: '정적분의 계산(4) : 절댓값 기호를 포함한 함수', hwp: '정적분의 계산(4) : 절댓값 기호를 포함한 함수' },
  { id: 'CAL-14-09', groupId: 'CAL-14', subject: 'calculus1', label: '정적분의 계산(5) : 다양한 조건이 주어진 경우', plain: '정적분의 계산(5) : 다양한 조건이 주어진 경우', hwp: '정적분의 계산(5) : 다양한 조건이 주어진 경우' },
  { id: 'CAL-14-10', groupId: 'CAL-14', subject: 'calculus1', label: '우함수 · 기함수의 정적분(1) : 피적분함수가 주어진 경우', plain: '우함수 · 기함수의 정적분(1) : 피적분함수가 주어진 경우', hwp: '우함수 · 기함수의 정적분(1) : 피적분함수가 주어진 경우' },
  { id: 'CAL-14-11', groupId: 'CAL-14', subject: 'calculus1', label: '우함수 · 기함수의 정적분(2) : 피적분함수가 주어지지 않은 경우', plain: '우함수 · 기함수의 정적분(2) : 피적분함수가 주어지지 않은 경우', hwp: '우함수 · 기함수의 정적분(2) : 피적분함수가 주어지지 않은 경우' },
  { id: 'CAL-14-12', groupId: 'CAL-14', subject: 'calculus1', label: '우함수 · 기함수의 정적분(3) : 이외의 경우가 주어진 경우', plain: '우함수 · 기함수의 정적분(3) : 이외의 경우가 주어진 경우', hwp: '우함수 · 기함수의 정적분(3) : 이외의 경우가 주어진 경우' },
  { id: 'CAL-14-13', groupId: 'CAL-14', subject: 'calculus1', label: '주기함수의 정적분 ($f(x)=f(x+k)$꼴의 함수의 정적분)', plain: '주기함수의 정적분 (f(x)=f(x+k)꼴의 함수의 정적분)', hwp: '주기함수의 정적분 ($f(x)=f(x+k)`$꼴의 함수의 정적분)' },
  { id: 'CAL-14-14', groupId: 'CAL-14', subject: 'calculus1', label: '직선 $x=k$에 대하여 대칭인 함수의 정적분', plain: '직선 x=k에 대하여 대칭인 함수의 정적분', hwp: '직선 $x=k`$에 대하여 대칭인 함수의 정적분' },
  { id: 'CAL-14-15', groupId: 'CAL-14', subject: 'calculus1', label: '평행이동, 대칭이동한 함수의 정적분', plain: '평행이동, 대칭이동한 함수의 정적분', hwp: '평행이동, 대칭이동한 함수의 정적분' },
  { id: 'CAL-14-16', groupId: 'CAL-14', subject: 'calculus1', label: '정적분을 포함한 등식(1) : 적분구간이 상수인 경우', plain: '정적분을 포함한 등식(1) : 적분구간이 상수인 경우', hwp: '정적분을 포함한 등식(1) : 적분구간이 상수인 경우' },
  { id: 'CAL-14-17', groupId: 'CAL-14', subject: 'calculus1', label: '정적분을 포함한 등식(2) : 적분구간에 변수가 있는 경우', plain: '정적분을 포함한 등식(2) : 적분구간에 변수가 있는 경우', hwp: '정적분을 포함한 등식(2) : 적분구간에 변수가 있는 경우' },
  { id: 'CAL-14-18', groupId: 'CAL-14', subject: 'calculus1', label: '정적분을 포함한 등식(3) : $\\int (x-t)f(t)\\,dt$꼴을 포함한 등식', plain: '정적분을 포함한 등식(3) : \\int (x-t)f(t)\\,dt꼴을 포함한 등식', hwp: '정적분을 포함한 등식(3) : $int{(x-t)f(t)`dt}`$꼴을 포함한 등식' },
  { id: 'CAL-14-19', groupId: 'CAL-14', subject: 'calculus1', label: '정적분으로 정의된 함수의 극대 · 극소', plain: '정적분으로 정의된 함수의 극대 · 극소', hwp: '정적분으로 정의된 함수의 극대 · 극소' },
  { id: 'CAL-14-20', groupId: 'CAL-14', subject: 'calculus1', label: '정적분으로 정의된 함수의 최대 · 최소', plain: '정적분으로 정의된 함수의 최대 · 최소', hwp: '정적분으로 정의된 함수의 최대 · 최소' },
  { id: 'CAL-14-21', groupId: 'CAL-14', subject: 'calculus1', label: '정적분으로 정의된 함수의 그래프', plain: '정적분으로 정의된 함수의 그래프', hwp: '정적분으로 정의된 함수의 그래프' },
  { id: 'CAL-14-22', groupId: 'CAL-14', subject: 'calculus1', label: '정적분으로 정의된 함수의 극한(1) : $\\lim_{x\\to 0}\\frac{1}{x}\\int f(t)\\,dt$꼴', plain: '정적분으로 정의된 함수의 극한(1) : \\lim_{x\\to 0}\\frac{1}{x}\\int f(t)\\,dt꼴', hwp: '정적분으로 정의된 함수의 극한(1) : $lim_{x`->`0}{1 overx int{f(t)`dt}`$꼴' },
  { id: 'CAL-14-23', groupId: 'CAL-14', subject: 'calculus1', label: '정적분으로 정의된 함수의 극한(2) : $\\lim_{x\\to a}\\frac{1}{x-a}\\int f(t)\\,dt$꼴', plain: '정적분으로 정의된 함수의 극한(2) : \\lim_{x\\to a}\\frac{1}{x-a}\\int f(t)\\,dt꼴', hwp: '정적분으로 정의된 함수의 극한(2) : $lim_{x`->`a}{1 over {x-a} int{f(t)`dt}`$꼴' },
  { id: 'CAL-15-01', groupId: 'CAL-15', subject: 'calculus1', label: '정적분과 넓이의 관계', plain: '정적분과 넓이의 관계', hwp: '정적분과 넓이의 관계' },
  { id: 'CAL-15-02', groupId: 'CAL-15', subject: 'calculus1', label: '곡선과 x축 사이의 넓이', plain: '곡선과 x축 사이의 넓이', hwp: '곡선과 x축 사이의 넓이' },
  { id: 'CAL-15-03', groupId: 'CAL-15', subject: 'calculus1', label: '곡선과 y축 사이의 넓이', plain: '곡선과 y축 사이의 넓이', hwp: '곡선과 y축 사이의 넓이' },
  { id: 'CAL-15-04', groupId: 'CAL-15', subject: 'calculus1', label: '곡선과 직선 사이의 넓이', plain: '곡선과 직선 사이의 넓이', hwp: '곡선과 직선 사이의 넓이' },
  { id: 'CAL-15-05', groupId: 'CAL-15', subject: 'calculus1', label: '곡선과 접선으로 둘러싸인 도형의 넓이', plain: '곡선과 접선으로 둘러싸인 도형의 넓이', hwp: '곡선과 접선으로 둘러싸인 도형의 넓이' },
  { id: 'CAL-15-06', groupId: 'CAL-15', subject: 'calculus1', label: '두 곡선 사이의 넓이', plain: '두 곡선 사이의 넓이', hwp: '두 곡선 사이의 넓이' },
  { id: 'CAL-15-07', groupId: 'CAL-15', subject: 'calculus1', label: '두 곡선 사이의 넓이의 응용', plain: '두 곡선 사이의 넓이의 응용', hwp: '두 곡선 사이의 넓이의 응용' },
  { id: 'CAL-15-08', groupId: 'CAL-15', subject: 'calculus1', label: '두 도형의 넓이가 같을 조건', plain: '두 도형의 넓이가 같을 조건', hwp: '두 도형의 넓이가 같을 조건' },
  { id: 'CAL-15-09', groupId: 'CAL-15', subject: 'calculus1', label: '두 곡선 사이의 넓이의 활용(1) : 이등분', plain: '두 곡선 사이의 넓이의 활용(1) : 이등분', hwp: '두 곡선 사이의 넓이의 활용(1) : 이등분' },
  { id: 'CAL-15-10', groupId: 'CAL-15', subject: 'calculus1', label: '두 곡선 사이의 넓이의 활용(2) : 넓이의 최솟값', plain: '두 곡선 사이의 넓이의 활용(2) : 넓이의 최솟값', hwp: '두 곡선 사이의 넓이의 활용(2) : 넓이의 최솟값' },
  { id: 'CAL-15-11', groupId: 'CAL-15', subject: 'calculus1', label: '두 곡선 사이의 넓이의 활용(3) : 이외의 조건이 주어진 경우', plain: '두 곡선 사이의 넓이의 활용(3) : 이외의 조건이 주어진 경우', hwp: '두 곡선 사이의 넓이의 활용(3) : 이외의 조건이 주어진 경우' },
  { id: 'CAL-15-12', groupId: 'CAL-15', subject: 'calculus1', label: '함수와 그 역함수의 정적분', plain: '함수와 그 역함수의 정적분', hwp: '함수와 그 역함수의 정적분' },
  { id: 'CAL-15-13', groupId: 'CAL-15', subject: 'calculus1', label: '함수와 그 역함수의 그래프로 둘러싸인 도형의 넓이', plain: '함수와 그 역함수의 그래프로 둘러싸인 도형의 넓이', hwp: '함수와 그 역함수의 그래프로 둘러싸인 도형의 넓이' },
  { id: 'CAL-16-01', groupId: 'CAL-16', subject: 'calculus1', label: '위치와 위치의 변화량', plain: '위치와 위치의 변화량', hwp: '위치와 위치의 변화량' },
  { id: 'CAL-16-02', groupId: 'CAL-16', subject: 'calculus1', label: '움직인 거리(1) : 직선 운동에서의 위치와 움직인 거리', plain: '움직인 거리(1) : 직선 운동에서의 위치와 움직인 거리', hwp: '움직인 거리(1) : 직선 운동에서의 위치와 움직인 거리' },
  { id: 'CAL-16-03', groupId: 'CAL-16', subject: 'calculus1', label: '움직인 거리(2) : 상하 운동에서의 위치와 움직인 거리', plain: '움직인 거리(2) : 상하 운동에서의 위치와 움직인 거리', hwp: '움직인 거리(2) : 상하 운동에서의 위치와 움직인 거리' },
  { id: 'CAL-16-04', groupId: 'CAL-16', subject: 'calculus1', label: '움직인 거리(3) : 그래프에서의 위치와 움직인 거리', plain: '움직인 거리(3) : 그래프에서의 위치와 움직인 거리', hwp: '움직인 거리(3) : 그래프에서의 위치와 움직인 거리' },
  { id: 'STA-01-01', groupId: 'STA-01', subject: 'statistics', label: '중복순열의 수', plain: '중복순열의 수', hwp: '중복순열의 수' },
  { id: 'STA-01-02', groupId: 'STA-01', subject: 'statistics', label: '신호의 개수', plain: '신호의 개수', hwp: '신호의 개수' },
  { id: 'STA-01-03', groupId: 'STA-01', subject: 'statistics', label: '자연수의 개수', plain: '자연수의 개수', hwp: '자연수의 개수' },
  { id: 'STA-01-04', groupId: 'STA-01', subject: 'statistics', label: '함수의 개수(1) 중복순열의 수', plain: '함수의 개수(1) 중복순열의 수', hwp: '함수의 개수(1) 중복순열의 수' },
  { id: 'STA-01-05', groupId: 'STA-01', subject: 'statistics', label: '같은 것이 있는 순열의 수', plain: '같은 것이 있는 순열의 수', hwp: '같은 것이 있는 순열의 수' },
  { id: 'STA-01-06', groupId: 'STA-01', subject: 'statistics', label: '순서가 정해진 경우의 수', plain: '순서가 정해진 경우의 수', hwp: '순서가 정해진 경우의 수' },
  { id: 'STA-01-07', groupId: 'STA-01', subject: 'statistics', label: '최단 거리로 가는 경우의 수(1) 장애물이 없는 경우', plain: '최단 거리로 가는 경우의 수(1) 장애물이 없는 경우', hwp: '최단 거리로 가는 경우의 수(1) 장애물이 없는 경우' },
  { id: 'STA-01-08', groupId: 'STA-01', subject: 'statistics', label: '최단 거리로 가는 경우의 수(2) 장애물이 있는 경우', plain: '최단 거리로 가는 경우의 수(2) 장애물이 있는 경우', hwp: '최단 거리로 가는 경우의 수(2) 장애물이 있는 경우' },
  { id: 'STA-02-01', groupId: 'STA-02', subject: 'statistics', label: '중복조합의 수', plain: '중복조합의 수', hwp: '중복조합의 수' },
  { id: 'STA-02-02', groupId: 'STA-02', subject: 'statistics', label: '‘적어도’의 조건이 있는 중복조합의 수', plain: '‘적어도’의 조건이 있는 중복조합의 수', hwp: '‘적어도’의 조건이 있는 중복조합의 수' },
  { id: 'STA-02-03', groupId: 'STA-02', subject: 'statistics', label: '다항식의 전개식에서 항의 개수', plain: '다항식의 전개식에서 항의 개수', hwp: '다항식의 전개식에서 항의 개수' },
  { id: 'STA-02-04', groupId: 'STA-02', subject: 'statistics', label: '방정식과 부등식의 해의 개수', plain: '방정식과 부등식의 해의 개수', hwp: '방정식과 부등식의 해의 개수' },
  { id: 'STA-02-05', groupId: 'STA-02', subject: 'statistics', label: '함수의 개수(2) 중복조합의 수', plain: '함수의 개수(2) 중복조합의 수', hwp: '함수의 개수(2) 중복조합의 수' },
  { id: 'STA-02-06', groupId: 'STA-02', subject: 'statistics', label: '함수의 개수(3) 그 외', plain: '함수의 개수(3) 그 외', hwp: '함수의 개수(3) 그 외' },
  { id: 'STA-03-01', groupId: 'STA-03', subject: 'statistics', label: '이항정리', plain: '이항정리', hwp: '이항정리' },
  { id: 'STA-03-02', groupId: 'STA-03', subject: 'statistics', label: '$(a+b)^{n}$의 전개식', plain: '(a+b)^{n}의 전개식', hwp: '$(a+b)^{`n}`$의 전개식' },
  { id: 'STA-03-03', groupId: 'STA-03', subject: 'statistics', label: '$(a+b)(c+d)^{n}$의 전개식', plain: '(a+b)(c+d)^{n}의 전개식', hwp: '$(a+b)(c+d)^{`n}`$의 전개식' },
  { id: 'STA-03-04', groupId: 'STA-03', subject: 'statistics', label: '$(a+b)^{m}(c+d)^{n}$의 전개식', plain: '(a+b)^{m}(c+d)^{n}의 전개식', hwp: '$(a+b)^{`m}(c+d)^{`n}`$의 전개식' },
  { id: 'STA-03-05', groupId: 'STA-03', subject: 'statistics', label: '$(a+b+c)^{n}$의 전개식', plain: '(a+b+c)^{n}의 전개식', hwp: '$(a+b+c)^{`n}`$의 전개식' },
  { id: 'STA-03-06', groupId: 'STA-03', subject: 'statistics', label: '이항계수의 성질', plain: '이항계수의 성질', hwp: '이항계수의 성질' },
  { id: 'STA-03-07', groupId: 'STA-03', subject: 'statistics', label: '$(1+x)^{n}$의 전개식의 활용', plain: '(1+x)^{n}의 전개식의 활용', hwp: '$(1+x)^{`n}`$의 전개식의 활용' },
  { id: 'STA-03-08', groupId: 'STA-03', subject: 'statistics', label: '파스칼의 삼각형', plain: '파스칼의 삼각형', hwp: '파스칼의 삼각형' },
  { id: 'STA-03-09', groupId: 'STA-03', subject: 'statistics', label: '이하정리(대수 이수한 경우)', plain: '이하정리(대수 이수한 경우)', hwp: '이하정리(대수 이수한 경우)' },
  { id: 'STA-04-01', groupId: 'STA-04', subject: 'statistics', label: '시행과 사건', plain: '시행과 사건', hwp: '시행과 사건' },
  { id: 'STA-04-02', groupId: 'STA-04', subject: 'statistics', label: '수학적 확률', plain: '수학적 확률', hwp: '수학적 확률' },
  { id: 'STA-04-03', groupId: 'STA-04', subject: 'statistics', label: '순열을 이용하는 확률', plain: '순열을 이용하는 확률', hwp: '순열을 이용하는 확률' },
  { id: 'STA-04-04', groupId: 'STA-04', subject: 'statistics', label: '중복순열을 이용하는 확률', plain: '중복순열을 이용하는 확률', hwp: '중복순열을 이용하는 확률' },
  { id: 'STA-04-05', groupId: 'STA-04', subject: 'statistics', label: '같은 것이 있는 순열을 이용하는 확률', plain: '같은 것이 있는 순열을 이용하는 확률', hwp: '같은 것이 있는 순열을 이용하는 확률' },
  { id: 'STA-04-06', groupId: 'STA-04', subject: 'statistics', label: '조합을 이용하는 확률', plain: '조합을 이용하는 확률', hwp: '조합을 이용하는 확률' },
  { id: 'STA-04-07', groupId: 'STA-04', subject: 'statistics', label: '중복조합을 이용하는 확률', plain: '중복조합을 이용하는 확률', hwp: '중복조합을 이용하는 확률' },
  { id: 'STA-04-08', groupId: 'STA-04', subject: 'statistics', label: '통계적 확률', plain: '통계적 확률', hwp: '통계적 확률' },
  { id: 'STA-04-09', groupId: 'STA-04', subject: 'statistics', label: '기하적 확률', plain: '기하적 확률', hwp: '기하적 확률' },
  { id: 'STA-04-10', groupId: 'STA-04', subject: 'statistics', label: '확률의 기본 성질', plain: '확률의 기본 성질', hwp: '확률의 기본 성질' },
  { id: 'STA-05-01', groupId: 'STA-05', subject: 'statistics', label: '확률의 덧셈정리와 여사건의 확률', plain: '확률의 덧셈정리와 여사건의 확률', hwp: '확률의 덧셈정리와 여사건의 확률' },
  { id: 'STA-05-02', groupId: 'STA-05', subject: 'statistics', label: '확률의 덧셈정리(1) 배반사건이 아닌 경우', plain: '확률의 덧셈정리(1) 배반사건이 아닌 경우', hwp: '확률의 덧셈정리(1) 배반사건이 아닌 경우' },
  { id: 'STA-05-03', groupId: 'STA-05', subject: 'statistics', label: '확률의 덧셈정리(2) 배반사건인 경우', plain: '확률의 덧셈정리(2) 배반사건인 경우', hwp: '확률의 덧셈정리(2) 배반사건인 경우' },
  { id: 'STA-05-04', groupId: 'STA-05', subject: 'statistics', label: '여사건의 확률(1) \'적어도\'의 조건이 있는 경우', plain: '여사건의 확률(1) \'적어도\'의 조건이 있는 경우', hwp: '여사건의 확률(1) \'적어도\'의 조건이 있는 경우' },
  { id: 'STA-05-05', groupId: 'STA-05', subject: 'statistics', label: '여사건의 확률(2) \'이상\', \'이하\', \'아닌\'의 조건이 있는 경우', plain: '여사건의 확률(2) \'이상\', \'이하\', \'아닌\'의 조건이 있는 경우', hwp: '여사건의 확률(2) \'이상\', \'이하\', \'아닌\'의 조건이 있는 경우' },
  { id: 'STA-06-01', groupId: 'STA-06', subject: 'statistics', label: '조건부확률의 계산', plain: '조건부확률의 계산', hwp: '조건부확률의 계산' },
  { id: 'STA-06-02', groupId: 'STA-06', subject: 'statistics', label: '조건부확률(1) 확률이 직접 주어진 경우', plain: '조건부확률(1) 확률이 직접 주어진 경우', hwp: '조건부확률(1) 확률이 직접 주어진 경우' },
  { id: 'STA-06-03', groupId: 'STA-06', subject: 'statistics', label: '조건부확률(2) 표, 문장 등으로 확률이 주어진 경우', plain: '조건부확률(2) 표, 문장 등으로 확률이 주어진 경우', hwp: '조건부확률(2) 표, 문장 등으로 확률이 주어진 경우' },
  { id: 'STA-06-04', groupId: 'STA-06', subject: 'statistics', label: '확률의 곱셈정리(1) $\\mathrm{P}(A\\cap B)=P(A)P(B\\mid A)$', plain: '확률의 곱셈정리(1) \\mathrm{P}(A\\cap B)=P(A)P(B\\mid A)', hwp: '확률의 곱셈정리(1) $rmP(A SMALLINTER B) = P(A)P(B `vert`A)$' },
  { id: 'STA-06-05', groupId: 'STA-06', subject: 'statistics', label: '확률의 곱셈정리(2) $\\mathrm{P}(E)=P(A\\cap E)+P(A^{c}\\cap E)$', plain: '확률의 곱셈정리(2) \\mathrm{P}(E)=P(A\\cap E)+P(A^{c}\\cap E)', hwp: '확률의 곱셈정리(2) $rmP(E) = P(A smallinterE)+P(A^c smallinterE)$' },
  { id: 'STA-06-06', groupId: 'STA-06', subject: 'statistics', label: '조건부확률과 확률의 곱셈정리', plain: '조건부확률과 확률의 곱셈정리', hwp: '조건부확률과 확률의 곱셈정리' },
  { id: 'STA-07-01', groupId: 'STA-07', subject: 'statistics', label: '사건의 독립과 종속의 판정', plain: '사건의 독립과 종속의 판정', hwp: '사건의 독립과 종속의 판정' },
  { id: 'STA-07-02', groupId: 'STA-07', subject: 'statistics', label: '사건의 독립과 종속의 성질', plain: '사건의 독립과 종속의 성질', hwp: '사건의 독립과 종속의 성질' },
  { id: 'STA-07-03', groupId: 'STA-07', subject: 'statistics', label: '독립 사건의 확률(1) 확률이 직접 주어진 경우', plain: '독립 사건의 확률(1) 확률이 직접 주어진 경우', hwp: '독립 사건의 확률(1) 확률이 직접 주어진 경우' },
  { id: 'STA-07-04', groupId: 'STA-07', subject: 'statistics', label: '독립 사건의 확률(2) 표, 문장 등으로 확률이 주어진 경우', plain: '독립 사건의 확률(2) 표, 문장 등으로 확률이 주어진 경우', hwp: '독립 사건의 확률(2) 표, 문장 등으로 확률이 주어진 경우' },
  { id: 'STA-07-05', groupId: 'STA-07', subject: 'statistics', label: '독립시행의 확률(1)', plain: '독립시행의 확률(1)', hwp: '독립시행의 확률(1)' },
  { id: 'STA-07-06', groupId: 'STA-07', subject: 'statistics', label: '독립시행의 확률(2)', plain: '독립시행의 확률(2)', hwp: '독립시행의 확률(2)' },
  { id: 'STA-08-01', groupId: 'STA-08', subject: 'statistics', label: '확률변수와 확률분포', plain: '확률변수와 확률분포', hwp: '확률변수와 확률분포' },
  { id: 'STA-08-02', groupId: 'STA-08', subject: 'statistics', label: '확률질량함수', plain: '확률질량함수', hwp: '확률질량함수' },
  { id: 'STA-08-03', groupId: 'STA-08', subject: 'statistics', label: '확률질량함수의 성질(1) 모든 확률의 합은 1이다.', plain: '확률질량함수의 성질(1) 모든 확률의 합은 1이다.', hwp: '확률질량함수의 성질(1) 모든 확률의 합은 1이다.' },
  { id: 'STA-08-04', groupId: 'STA-08', subject: 'statistics', label: '확률질량함수의 성질(2) $\\mathrm{P}(a\\leq \\mathrm{X}\\leq b)$', plain: '확률질량함수의 성질(2) \\mathrm{P}(a\\leq \\mathrm{X}\\leq b)', hwp: '확률질량함수의 성질(2) $rmP(ita<= rmX <= itb)`$' },
  { id: 'STA-08-05', groupId: 'STA-08', subject: 'statistics', label: '이산확률변수의 확률', plain: '이산확률변수의 확률', hwp: '이산확률변수의 확률' },
  { id: 'STA-08-06', groupId: 'STA-08', subject: 'statistics', label: '확률밀도함수', plain: '확률밀도함수', hwp: '확률밀도함수' },
  { id: 'STA-08-07', groupId: 'STA-08', subject: 'statistics', label: '확률밀도함수의 성질', plain: '확률밀도함수의 성질', hwp: '확률밀도함수의 성질' },
  { id: 'STA-08-08', groupId: 'STA-08', subject: 'statistics', label: '연속확률변수의 확률', plain: '연속확률변수의 확률', hwp: '연속확률변수의 확률' },
  { id: 'STA-08-09', groupId: 'STA-08', subject: 'statistics', label: '확률밀도함수의 성질(미적분1 이수한 경우)', plain: '확률밀도함수의 성질(미적분1 이수한 경우)', hwp: '확률밀도함수의 성질(미적분1 이수한 경우)' },
  { id: 'STA-09-01', groupId: 'STA-09', subject: 'statistics', label: '확률변수의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우', plain: '확률변수의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우', hwp: '확률변수의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우' },
  { id: 'STA-09-02', groupId: 'STA-09', subject: 'statistics', label: '확률변수의 평균, 분산, 표준편차(2) 확률분포가 주어지 않은 경우', plain: '확률변수의 평균, 분산, 표준편차(2) 확률분포가 주어지 않은 경우', hwp: '확률변수의 평균, 분산, 표준편차(2) 확률분포가 주어지 않은 경우' },
  { id: 'STA-09-03', groupId: 'STA-09', subject: 'statistics', label: '기댓값', plain: '기댓값', hwp: '기댓값' },
  { id: 'STA-09-04', groupId: 'STA-09', subject: 'statistics', label: '확률변수 $a\\mathrm{X}+b$의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우', plain: '확률변수 a\\mathrm{X}+b의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우', hwp: '확률변수 $a rmX+ itb`$의 평균, 분산, 표준편차(1) 확률분포가 주어진 경우' },
  { id: 'STA-09-05', groupId: 'STA-09', subject: 'statistics', label: '확률변수 $a\\mathrm{X}+b$의 평균, 분산, 표준편차(2) 확률분포가 주어지지 않은 경우', plain: '확률변수 a\\mathrm{X}+b의 평균, 분산, 표준편차(2) 확률분포가 주어지지 않은 경우', hwp: '확률변수 $a rmX+ itb`$의 평균, 분산, 표준편차(2) 확률분포가 주어지지 않은 경우' },
  { id: 'STA-10-01', groupId: 'STA-10', subject: 'statistics', label: '이항분포', plain: '이항분포', hwp: '이항분포' },
  { id: 'STA-10-02', groupId: 'STA-10', subject: 'statistics', label: '이항분포에서의 확률', plain: '이항분포에서의 확률', hwp: '이항분포에서의 확률' },
  { id: 'STA-10-03', groupId: 'STA-10', subject: 'statistics', label: '이항분포에서의 평균, 분산, 표준편차(1) 이항분포가 주어진 경우', plain: '이항분포에서의 평균, 분산, 표준편차(1) 이항분포가 주어진 경우', hwp: '이항분포에서의 평균, 분산, 표준편차(1) 이항분포가 주어진 경우' },
  { id: 'STA-10-04', groupId: 'STA-10', subject: 'statistics', label: '이항분포에서의 평균, 분산, 표준편차(2) 이항분포가 주어지지 않은 경우', plain: '이항분포에서의 평균, 분산, 표준편차(2) 이항분포가 주어지지 않은 경우', hwp: '이항분포에서의 평균, 분산, 표준편차(2) 이항분포가 주어지지 않은 경우' },
  { id: 'STA-10-05', groupId: 'STA-10', subject: 'statistics', label: '확률변수 $a\\mathrm{X}+b$의 평균, 분산, 표준편차(3) 이항분포를 따르는 경우(실생활문제)', plain: '확률변수 a\\mathrm{X}+b의 평균, 분산, 표준편차(3) 이항분포를 따르는 경우(실생활문제)', hwp: '확률변수 $a rmX+ itb`$의 평균, 분산, 표준편차(3) 이항분포를 따르는 경우(실생활문제)' },
  { id: 'STA-10-06', groupId: 'STA-10', subject: 'statistics', label: '큰수의 법칙', plain: '큰수의 법칙', hwp: '큰수의 법칙' },
  { id: 'STA-11-01', groupId: 'STA-11', subject: 'statistics', label: '정규분포', plain: '정규분포', hwp: '정규분포' },
  { id: 'STA-11-02', groupId: 'STA-11', subject: 'statistics', label: '정규분포곡선의 성질', plain: '정규분포곡선의 성질', hwp: '정규분포곡선의 성질' },
  { id: 'STA-11-03', groupId: 'STA-11', subject: 'statistics', label: '정규분포에서의 확률', plain: '정규분포에서의 확률', hwp: '정규분포에서의 확률' },
  { id: 'STA-11-04', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 표준화', plain: '정규분포의 표준화', hwp: '정규분포의 표준화' },
  { id: 'STA-11-05', groupId: 'STA-11', subject: 'statistics', label: '표준화하여 확률 구하기', plain: '표준화하여 확률 구하기', hwp: '표준화하여 확률 구하기' },
  { id: 'STA-11-06', groupId: 'STA-11', subject: 'statistics', label: '표준화하여 미지수의 값 구하기', plain: '표준화하여 미지수의 값 구하기', hwp: '표준화하여 미지수의 값 구하기' },
  { id: 'STA-11-07', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 활용(1) 확률 구하기', plain: '정규분포의 활용(1) 확률 구하기', hwp: '정규분포의 활용(1) 확률 구하기' },
  { id: 'STA-11-08', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 활용(2) 도수 구하기', plain: '정규분포의 활용(2) 도수 구하기', hwp: '정규분포의 활용(2) 도수 구하기' },
  { id: 'STA-11-09', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 활용(3) 미지수의 값 구하기', plain: '정규분포의 활용(3) 미지수의 값 구하기', hwp: '정규분포의 활용(3) 미지수의 값 구하기' },
  { id: 'STA-11-10', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 활용(4) 최대, 최소를 만족시키는 값 구하기', plain: '정규분포의 활용(4) 최대, 최소를 만족시키는 값 구하기', hwp: '정규분포의 활용(4) 최대, 최소를 만족시키는 값 구하기' },
  { id: 'STA-11-11', groupId: 'STA-11', subject: 'statistics', label: '정규분포의 활용(5) 표준화하여 확률 비교하기', plain: '정규분포의 활용(5) 표준화하여 확률 비교하기', hwp: '정규분포의 활용(5) 표준화하여 확률 비교하기' },
  { id: 'STA-11-12', groupId: 'STA-11', subject: 'statistics', label: '이항분포와 정규분포의 관계', plain: '이항분포와 정규분포의 관계', hwp: '이항분포와 정규분포의 관계' },
  { id: 'STA-11-13', groupId: 'STA-11', subject: 'statistics', label: '이항분포와 정규분포의 관계의 활용(1) 확률 구하기', plain: '이항분포와 정규분포의 관계의 활용(1) 확률 구하기', hwp: '이항분포와 정규분포의 관계의 활용(1) 확률 구하기' },
  { id: 'STA-11-14', groupId: 'STA-11', subject: 'statistics', label: '이항분포와 정규분포의 관계의 활용(2) 미지수의 값 구하기', plain: '이항분포와 정규분포의 관계의 활용(2) 미지수의 값 구하기', hwp: '이항분포와 정규분포의 관계의 활용(2) 미지수의 값 구하기' },
  { id: 'STA-11-15', groupId: 'STA-11', subject: 'statistics', label: '확률분포(대수, 미적분1을 이수한 경우)', plain: '확률분포(대수, 미적분1을 이수한 경우)', hwp: '확률분포(대수, 미적분1을 이수한 경우)' },
  { id: 'STA-12-01', groupId: 'STA-12', subject: 'statistics', label: '모집단과 표본', plain: '모집단과 표본', hwp: '모집단과 표본' },
  { id: 'STA-13-01', groupId: 'STA-13', subject: 'statistics', label: '모평균과 표본평균', plain: '모평균과 표본평균', hwp: '모평균과 표본평균' },
  { id: 'STA-13-02', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 평균, 분산, 표준편차(1) 모평균, 모표준편차가 주어진 경우', plain: '표본평균의 평균, 분산, 표준편차(1) 모평균, 모표준편차가 주어진 경우', hwp: '표본평균의 평균, 분산, 표준편차(1) 모평균, 모표준편차가 주어진 경우' },
  { id: 'STA-13-03', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 평균, 분산, 표준편차(2) 모집단의 확률분포가 주어진 경우', plain: '표본평균의 평균, 분산, 표준편차(2) 모집단의 확률분포가 주어진 경우', hwp: '표본평균의 평균, 분산, 표준편차(2) 모집단의 확률분포가 주어진 경우' },
  { id: 'STA-13-04', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 평균, 분산, 표준편차(3) 모집단이 주어진 경우', plain: '표본평균의 평균, 분산, 표준편차(3) 모집단이 주어진 경우', hwp: '표본평균의 평균, 분산, 표준편차(3) 모집단이 주어진 경우' },
  { id: 'STA-13-05', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 확률(1) 그 외', plain: '표본평균의 확률(1) 그 외', hwp: '표본평균의 확률(1) 그 외' },
  { id: 'STA-13-06', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 확률(2) 표본의 크기 구하기', plain: '표본평균의 확률(2) 표본의 크기 구하기', hwp: '표본평균의 확률(2) 표본의 크기 구하기' },
  { id: 'STA-13-07', groupId: 'STA-13', subject: 'statistics', label: '표본평균의 확률(3) 미지수의 값 구하기', plain: '표본평균의 확률(3) 미지수의 값 구하기', hwp: '표본평균의 확률(3) 미지수의 값 구하기' },
  { id: 'STA-13-08', groupId: 'STA-13', subject: 'statistics', label: '모평균의 추정(1) 모표준편차가 주어진 경우', plain: '모평균의 추정(1) 모표준편차가 주어진 경우', hwp: '모평균의 추정(1) 모표준편차가 주어진 경우' },
  { id: 'STA-13-09', groupId: 'STA-13', subject: 'statistics', label: '모평균의 추정(2) 표본표준편차가 주어진 경우', plain: '모평균의 추정(2) 표본표준편차가 주어진 경우', hwp: '모평균의 추정(2) 표본표준편차가 주어진 경우' },
  { id: 'STA-13-10', groupId: 'STA-13', subject: 'statistics', label: '모평균의 추정(3) 표본의 크기 구하기', plain: '모평균의 추정(3) 표본의 크기 구하기', hwp: '모평균의 추정(3) 표본의 크기 구하기' },
  { id: 'STA-13-11', groupId: 'STA-13', subject: 'statistics', label: '신뢰구간의 길이(1) 모평균에 대한 신뢰구간의 길이', plain: '신뢰구간의 길이(1) 모평균에 대한 신뢰구간의 길이', hwp: '신뢰구간의 길이(1) 모평균에 대한 신뢰구간의 길이' },
  { id: 'STA-13-12', groupId: 'STA-13', subject: 'statistics', label: '신뢰구간의 길이(2) 표본의 크기 구하기', plain: '신뢰구간의 길이(2) 표본의 크기 구하기', hwp: '신뢰구간의 길이(2) 표본의 크기 구하기' },
  { id: 'STA-13-13', groupId: 'STA-13', subject: 'statistics', label: '신뢰구간의 길이(3) 신뢰도 구하기', plain: '신뢰구간의 길이(3) 신뢰도 구하기', hwp: '신뢰구간의 길이(3) 신뢰도 구하기' },
  { id: 'STA-13-14', groupId: 'STA-13', subject: 'statistics', label: '모평균과 표본평균의 차', plain: '모평균과 표본평균의 차', hwp: '모평균과 표본평균의 차' },
  { id: 'STA-13-15', groupId: 'STA-13', subject: 'statistics', label: '신뢰구간의 성질', plain: '신뢰구간의 성질', hwp: '신뢰구간의 성질' },
  { id: 'STA-14-01', groupId: 'STA-14', subject: 'statistics', label: '모비율과 표본비율', plain: '모비율과 표본비율', hwp: '모비율과 표본비율' },
  { id: 'STA-14-02', groupId: 'STA-14', subject: 'statistics', label: '표본비율의 평균, 분산, 표준편차', plain: '표본비율의 평균, 분산, 표준편차', hwp: '표본비율의 평균, 분산, 표준편차' },
  { id: 'STA-14-03', groupId: 'STA-14', subject: 'statistics', label: '표본비율의 확률', plain: '표본비율의 확률', hwp: '표본비율의 확률' },
  { id: 'STA-14-04', groupId: 'STA-14', subject: 'statistics', label: '모비율의 추정', plain: '모비율의 추정', hwp: '모비율의 추정' },
  { id: 'STA-14-05', groupId: 'STA-14', subject: 'statistics', label: '모비율의 신뢰구간의 길이', plain: '모비율의 신뢰구간의 길이', hwp: '모비율의 신뢰구간의 길이' },
];

export const groupsBySubject = (s: SubjectSlug) =>
  UNIT_GROUPS.filter((g) => g.subject === s);

export const typesInGroup = (groupId: string) =>
  UNIT_TYPES.filter((t) => t.groupId === groupId);

export const findType = (id: string) => UNIT_TYPES.find((t) => t.id === id);

/** 1차 분류 프롬프트용 소단원 목록 (과목당 14~19줄) */
export const groupPromptList = (s: SubjectSlug) =>
  groupsBySubject(s).map((g) => `${g.id} | ${g.l1} > ${g.l2} > ${g.l3}`).join('\n');

/** 2차 분류 프롬프트용 세부유형 목록 (소단원당 1~24줄) */
export const typePromptList = (groupId: string) =>
  typesInGroup(groupId).map((t) => `${t.id} | ${t.plain}`).join('\n');
